# See packaging for various base options
FROM flatironinstitute/triqs:base
ARG APPNAME=triqs

ARG BUILDUID=983
RUN useradd -u $BUILDUID -m build

ENV SRC=/src \
    BUILD=/home/build \
    INSTALL=/usr/local \
    PYTHONPATH=/usr/local/lib/python$PYTHON_VERSION/site-packages \
    CMAKE_PREFIX_PATH=/usr/lib/cmake/$APPNAME \
    OPENBLAS_NUM_THREADS=1 \
    MKL_NUM_THREADS=1

# Hacky patch for matplotlib sphinx bug (https://github.com/matplotlib/matplotlib/pull/12456?)
RUN ln -s /src /home/src

# Build and install clair so that clair-c2py is available for Python binding regeneration.
# Set WITH_CLAIR=false to skip (e.g. for platforms that do not regenerate the Python bindings).
ARG WITH_CLAIR=true
RUN if [ "$WITH_CLAIR" = "true" ]; then \
      git clone https://github.com/flatironinstitute/clair --branch unstable $SRC/clair && \
      mkdir $BUILD/clair && \
      CXX="clang++-${LLVM}" CXXFLAGS="" CPLUS_INCLUDE_PATH="" cmake -S $SRC/clair -B $BUILD/clair -DBuild_Tests=OFF -DCMAKE_INSTALL_PREFIX=$INSTALL && \
      cmake --build $BUILD/clair && cmake --install $BUILD/clair; \
    fi

COPY --chown=build . $SRC/$APPNAME
WORKDIR $BUILD/$APPNAME
RUN chown build .
USER build
ARG BUILD_ID
ARG CMAKE_ARGS
ARG NCORES=4
RUN cmake $SRC/$APPNAME -DCMAKE_INSTALL_PREFIX=$INSTALL -DCLANG_OPT="$CXXFLAGS" $CMAKE_ARGS && make -j$NCORES || make -j1 VERBOSE=1
USER root
RUN make install
