"""
Generate gf_factories_*.hpp files with explicit template instantiations
and wrapper functions for the c2py port of gf_factories.

Produces 4 .hpp files:
  - gf_factories_hermitian.hpp: make_hermitian, make_real_in_tau, make_gf_dlr, fit_gf_dlr
  - gf_factories_fourier.hpp: make_gf_from_fourier (all overloads)
  - gf_factories_dlr_imtime.hpp: make_gf_dlr_imtime, make_gf_imtime
  - gf_factories_dlr_imfreq.hpp: make_gf_dlr_imfreq, make_gf_imfreq
"""

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

TARGETS = ["scalar_valued", "tensor_valued<1>", "matrix_valued", "tensor_valued<3>", "tensor_valued<4>"]
TARGET_RANK = {"scalar_valued": 0, "tensor_valued<1>": 1, "matrix_valued": 2, "tensor_valued<3>": 3, "tensor_valued<4>": 4}

# Targets used in hermitian functions (only rank 0, 2, 4)
HERMITIAN_TARGETS = ["scalar_valued", "matrix_valued", "tensor_valued<4>"]

# Targets limited for product mesh DLR (to avoid compile-time blowup)
PROD_DLR_TARGETS = ["scalar_valued", "matrix_valued"]

GF_TYPES = ["gf", "block_gf", "block2_gf"]
BLOCK_GF_TYPES = ["block_gf", "block2_gf"]
GF_VIEW_TYPES = {"gf": "gf_const_view", "block_gf": "block_gf_const_view", "block2_gf": "block2_gf_const_view"}

# (output_mesh, input_mesh) pairs for Matsubara/real Fourier
MATSUBARA_REAL_PAIRS = [("imfreq", "imtime"), ("imtime", "imfreq"), ("refreq", "retime"), ("retime", "refreq")]

# Fourier info keyed by input mesh: (output_mesh, extra_arg_type, uses_complex_t)
# uses_complex_t: True means return type is gf<out, T::complex_t>, False means gf<out, T>
FOURIER_GF_INFO = {
    "imtime": ("imfreq", "int", True),
    "imfreq": ("imtime", "int", False),
    "retime": ("refreq", "bool", True),
    "refreq": ("retime", "bool", False),
}

LATTICE_PAIRS = [("cyclat", "brzone"), ("brzone", "cyclat")]
TIME_MESHES = {"imtime", "retime"}
LATTICE_MESHES = ["brzone", "cyclat"]
DLR_INPUT_MESHES = ["dlr_imtime", "dlr_imfreq"]


def real_valued(target):
    """scalar_valued -> scalar_real_valued, matrix_valued -> matrix_real_valued, tensor_valued<N> -> tensor_real_valued<N>"""
    return target.replace("_valued", "_real_valued")


def complex_t(target):
    """T::complex_t: real targets -> complex, complex targets unchanged."""
    return target.replace("_real_valued", "_valued")


def known_moments_type(gf_type, target):
    """Type for known_moments parameter, keyed by gf_type."""
    r = TARGET_RANK[target] + 1
    if gf_type == "gf":
        return f"array_const_view<dcomplex, {r}>"
    elif gf_type == "block_gf":
        return f"std::vector<array<dcomplex, {r}>>"
    else:
        return f"std::vector<std::vector<array<dcomplex, {r}>>>"


HEADER = """\
// Generated by gf_factories.inst.py. Do not edit!
#pragma once

#include <triqs/gfs.hpp>
#include <triqs/gfs/functions/dlr.hpp>
#include <triqs/gfs/functions/imfreq.hpp>
#include <triqs/gfs/transform/fourier.hpp>
#include <triqs/mesh.hpp>

using namespace triqs::arrays;
using namespace triqs::gfs;
using namespace triqs::mesh;

"""


# ---------------------------------------------------------------------------
# Generate gf_factories_hermitian.hpp
# make_hermitian, make_real_in_tau, make_gf_dlr, fit_gf_dlr
# ---------------------------------------------------------------------------

def write_hermitian(f):
    f.write(HEADER)
    f.write("namespace triqs::gfs {\n\n")

    # --- make_hermitian ---
    f.write("  // make_hermitian: imfreq and imtime, target rank 0, 2, 4\n")
    for mesh in ["imfreq", "imtime"]:
        for target in HERMITIAN_TARGETS:
            for gf in GF_TYPES:
                view = GF_VIEW_TYPES[gf]
                f.write(f"  template {gf}<{mesh}, {target}> make_hermitian({view}<{mesh}, {target}> const &);\n")
    f.write("\n")

    # --- make_real_in_tau ---
    f.write("  // make_real_in_tau: imfreq only, target rank 0, 2, 4\n")
    for target in HERMITIAN_TARGETS:
        for gf in GF_TYPES:
            view = GF_VIEW_TYPES[gf]
            f.write(f"  template {gf}<imfreq, {target}> make_real_in_tau({view}<imfreq, {target}> const &);\n")
    f.write("\n")

    # --- make_gf_dlr (single mesh) ---
    f.write("  // make_gf_dlr: single mesh DLR conversions\n")
    for target in TARGETS:
        for gf in GF_TYPES:
            view = GF_VIEW_TYPES[gf]
            for in_mesh in DLR_INPUT_MESHES:
                f.write(f"  auto make_gf_dlr({view}<{in_mesh}, {target}> const &g) {{ return make_gf_dlr<0>(g); }}\n")
    f.write("\n")

    # --- fit_gf_dlr (single mesh) ---
    f.write("  // fit_gf_dlr: imtime -> dlr\n")
    for target in TARGETS:
        for gf in GF_TYPES:
            view = GF_VIEW_TYPES[gf]
            f.write(f"  auto fit_gf_dlr({view}<imtime, {target}> const &g, double w_max, double eps, bool symmetrize = false) {{ return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }}\n")
    f.write("\n")

    # --- make_gf_dlr (product mesh wrappers) ---
    f.write("  // make_gf_dlr: product mesh wrappers\n")
    for target in PROD_DLR_TARGETS:
        for gf in ["gf", "block_gf"]:
            view = GF_VIEW_TYPES[gf]
            for M in LATTICE_MESHES:
                for in_mesh in DLR_INPUT_MESHES:
                    f.write(f"  auto make_gf_dlr({view}<prod<{in_mesh}, {M}>, {target}> g) {{ return make_gf_dlr<0>(g); }}\n")
                    f.write(f"  auto make_gf_dlr({view}<prod<{M}, {in_mesh}>, {target}> g) {{ return make_gf_dlr<1>(g); }}\n")
    f.write("\n")

    # --- fit_gf_dlr (product mesh wrappers) ---
    f.write("  // fit_gf_dlr: product mesh wrappers\n")
    for target in PROD_DLR_TARGETS:
        for gf in ["gf", "block_gf"]:
            view = GF_VIEW_TYPES[gf]
            for M in LATTICE_MESHES:
                f.write(f"  auto fit_gf_dlr({view}<prod<imtime, {M}>, {target}> g, double w_max, double eps, bool symmetrize = false) {{ return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }}\n")
                f.write(f"  auto fit_gf_dlr({view}<prod<{M}, imtime>, {target}> g, double w_max, double eps, bool symmetrize = false) {{ return fit_gf_dlr<1>(g, w_max, eps, symmetrize); }}\n")
    f.write("\n")

    f.write("} // namespace triqs::gfs\n")


# ---------------------------------------------------------------------------
# Generate gf_factories_fourier.hpp
# make_gf_from_fourier: all overloads
# ---------------------------------------------------------------------------

def write_fourier(f):
    f.write(HEADER)
    f.write("namespace triqs::gfs {\n\n")

    for target in TARGETS:
        real_t = real_valued(target)
        rank = TARGET_RANK[target]
        f.write(f"  // === {target} (rank {rank}) ===\n\n")

        # ----------------------------------------------------------------
        # Matsubara / real-frequency Fourier
        # ----------------------------------------------------------------

        for m_in in FOURIER_GF_INFO:
            out_mesh, extra_arg, uses_ct = FOURIER_GF_INFO[m_in]
            has_real = m_in in TIME_MESHES

            f.write(f"  // {m_in} -> {out_mesh}\n")

            # gf: specialized overload with explicit return type and default 2nd arg
            # ONE instantiation covers both the no-arg and with-arg Python cases
            ret_t = complex_t(target) if uses_ct else target
            f.write(f"  template gf<{out_mesh}, {ret_t}> make_gf_from_fourier(gf_const_view<{m_in}, {target}>, {extra_arg});\n")
            if has_real:
                ret_t_real = complex_t(real_t) if uses_ct else real_t
                f.write(f"  template gf<{out_mesh}, {ret_t_real}> make_gf_from_fourier(gf_const_view<{m_in}, {real_t}>, {extra_arg});\n")

            # block_gf / block2_gf: variadic template (uses auto) needs wrapper functions for GCC compat
            for gf in BLOCK_GF_TYPES:
                view = GF_VIEW_TYPES[gf]
                # No extra args
                f.write(f"  auto make_gf_from_fourier({view}<{m_in}, {target}> const &g) {{ return make_gf_from_fourier<0>(g); }}\n")
                if has_real:
                    f.write(f"  auto make_gf_from_fourier({view}<{m_in}, {real_t}> const &g) {{ return make_gf_from_fourier<0>(g); }}\n")
                # With extra arg
                f.write(f"  auto make_gf_from_fourier({view}<{m_in}, {target}> const &g, {extra_arg} const &x) {{ return make_gf_from_fourier<0>(g, x); }}\n")
                if has_real:
                    f.write(f"  auto make_gf_from_fourier({view}<{m_in}, {real_t}> const &g, {extra_arg} const &x) {{ return make_gf_from_fourier<0>(g, x); }}\n")

            f.write("\n")

        # ----------------------------------------------------------------
        # Known moments overloads (all use auto return type in C++)
        # ----------------------------------------------------------------

        f.write(f"  // Known moments\n")
        for m_in in FOURIER_GF_INFO:
            out_mesh = FOURIER_GF_INFO[m_in][0]
            has_real = m_in in TIME_MESHES

            # gf: wrapper function for generic overload
            km_gf = known_moments_type("gf", target)
            f.write(f"  auto make_gf_from_fourier(gf_const_view<{m_in}, {target}> g, {out_mesh} const &m, {km_gf} const &km) {{ return make_gf_from_fourier<0>(g, m, km); }}\n")
            if has_real:
                f.write(f"  auto make_gf_from_fourier(gf_const_view<{m_in}, {real_t}> g, {out_mesh} const &m, {km_gf} const &km) {{ return make_gf_from_fourier<0>(g, m, km); }}\n")

            # block_gf: wrapper function for known_moments
            km_block = known_moments_type("block_gf", target)
            f.write(f"  auto make_gf_from_fourier(block_gf_const_view<{m_in}, {target}> const &g, {out_mesh} const &m, {km_block} const &km) {{ return make_gf_from_fourier<0>(g, m, km); }}\n")
            if has_real:
                f.write(f"  auto make_gf_from_fourier(block_gf_const_view<{m_in}, {real_t}> const &g, {out_mesh} const &m, {km_block} const &km) {{ return make_gf_from_fourier<0>(g, m, km); }}\n")

            # block2_gf: wrapper function for known_moments
            km_block2 = known_moments_type("block2_gf", target)
            f.write(f"  auto make_gf_from_fourier(block2_gf_const_view<{m_in}, {target}> const &g, {out_mesh} const &m, {km_block2} const &km) {{ return make_gf_from_fourier<0>(g, m, km); }}\n")
            if has_real:
                f.write(f"  auto make_gf_from_fourier(block2_gf_const_view<{m_in}, {real_t}> const &g, {out_mesh} const &m, {km_block2} const &km) {{ return make_gf_from_fourier<0>(g, m, km); }}\n")

        f.write("\n")

        # ----------------------------------------------------------------
        # Lattice Fourier (1 param, gf uses auto return, block_gf uses auto)
        # ----------------------------------------------------------------

        f.write(f"  // Lattice Fourier\n")
        for m_out, m_in in LATTICE_PAIRS:
            for gf in GF_TYPES:
                view = GF_VIEW_TYPES[gf]
                if gf == "gf":
                    f.write(f"  auto make_gf_from_fourier(gf_const_view<{m_in}, {target}> g) {{ return make_gf_from_fourier<0>(g); }}\n")
                else:
                    f.write(f"  auto make_gf_from_fourier({view}<{m_in}, {target}> const &g) {{ return make_gf_from_fourier<0>(g); }}\n")

        f.write("\n")

    # ----------------------------------------------------------------
    # Product mesh Fourier (wrappers)
    # ----------------------------------------------------------------

    f.write("  // Product mesh Fourier wrappers\n")
    for target in PROD_DLR_TARGETS:
        for lat, dlr in [('brzone', 'dlr_imfreq'), ('cyclat', 'dlr_imtime')]:
            lat_adj = 'cyclat' if lat == 'brzone' else 'brzone'
            dlr_adj = 'dlr_imtime' if dlr == 'dlr_imfreq' else 'dlr_imfreq'
            # gf
            f.write(f"  auto make_gf_from_fourier(gf_view<prod<{lat}, {dlr}>, {target}> g_in) {{\n")
            f.write(f"    return make_gf_from_fourier<0, 1>(g_in);\n")
            f.write(f"  }}\n")
            # block_gf
            f.write(f"  auto make_gf_from_fourier(block_gf_view<prod<{lat}, {dlr}>, {target}> g_in) {{\n")
            f.write(f"    return map_block_gf([](auto &&g_bl) {{ return make_gf_from_fourier<0, 1>(make_const_view(g_bl)); }}, g_in);\n")
            f.write(f"  }}\n")
    f.write("\n")

    f.write("} // namespace triqs::gfs\n")


# ---------------------------------------------------------------------------
# Generate gf_factories_dlr_imtime.hpp
# make_gf_dlr_imtime, make_gf_imtime
# ---------------------------------------------------------------------------

def write_dlr_imtime(f):
    f.write(HEADER)
    f.write("namespace triqs::gfs {\n\n")

    # --- make_gf_dlr_imtime (single mesh) ---
    f.write("  // make_gf_dlr_imtime: from dlr and dlr_imfreq\n")
    for target in TARGETS:
        for gf in GF_TYPES:
            view = GF_VIEW_TYPES[gf]
            for in_mesh in ["dlr", "dlr_imfreq"]:
                f.write(f"  auto make_gf_dlr_imtime({view}<{in_mesh}, {target}> const &g) {{ return make_gf_dlr_imtime<0>(g); }}\n")
    f.write("\n")

    # --- make_gf_imtime (single mesh) ---
    f.write("  // make_gf_imtime: from dlr, dlr_imtime, dlr_imfreq\n")
    for target in TARGETS:
        for gf in GF_TYPES:
            view = GF_VIEW_TYPES[gf]
            for in_mesh in ["dlr", "dlr_imtime", "dlr_imfreq"]:
                f.write(f"  auto make_gf_imtime({view}<{in_mesh}, {target}> const &g, long n_tau) {{ return make_gf_imtime<0>(g, n_tau); }}\n")
    f.write("\n")

    # --- make_gf_dlr_imtime (product mesh wrappers) ---
    f.write("  // make_gf_dlr_imtime: product mesh wrappers\n")
    for target in PROD_DLR_TARGETS:
        for gf in ["gf", "block_gf"]:
            view = GF_VIEW_TYPES[gf]
            for M in LATTICE_MESHES:
                f.write(f"  auto make_gf_dlr_imtime({view}<prod<dlr, {M}>, {target}> g) {{ return make_gf_dlr_imtime<0>(g); }}\n")
                f.write(f"  auto make_gf_dlr_imtime({view}<prod<{M}, dlr>, {target}> g) {{ return make_gf_dlr_imtime<1>(g); }}\n")
    f.write("\n")

    # --- make_gf_imtime (product mesh wrappers) ---
    f.write("  // make_gf_imtime: product mesh wrappers\n")
    for target in PROD_DLR_TARGETS:
        for gf in ["gf", "block_gf"]:
            view = GF_VIEW_TYPES[gf]
            for M in LATTICE_MESHES:
                f.write(f"  auto make_gf_imtime({view}<prod<dlr, {M}>, {target}> g, long n_tau) {{ return make_gf_imtime<0>(g, n_tau); }}\n")
                f.write(f"  auto make_gf_imtime({view}<prod<{M}, dlr>, {target}> g, long n_tau) {{ return make_gf_imtime<1>(g, n_tau); }}\n")
    f.write("\n")

    f.write("} // namespace triqs::gfs\n")


# ---------------------------------------------------------------------------
# Generate gf_factories_dlr_imfreq.hpp
# make_gf_dlr_imfreq, make_gf_imfreq
# ---------------------------------------------------------------------------

def write_dlr_imfreq(f):
    f.write(HEADER)
    f.write("namespace triqs::gfs {\n\n")

    # --- make_gf_dlr_imfreq (single mesh) ---
    f.write("  // make_gf_dlr_imfreq: from dlr and dlr_imtime\n")
    for target in TARGETS:
        for gf in GF_TYPES:
            view = GF_VIEW_TYPES[gf]
            for in_mesh in ["dlr", "dlr_imtime"]:
                f.write(f"  auto make_gf_dlr_imfreq({view}<{in_mesh}, {target}> const &g) {{ return make_gf_dlr_imfreq<0>(g); }}\n")
    f.write("\n")

    # --- make_gf_imfreq (single mesh) ---
    f.write("  // make_gf_imfreq: from dlr, dlr_imtime, dlr_imfreq\n")
    for target in TARGETS:
        for gf in GF_TYPES:
            view = GF_VIEW_TYPES[gf]
            for in_mesh in ["dlr", "dlr_imtime", "dlr_imfreq"]:
                f.write(f"  auto make_gf_imfreq({view}<{in_mesh}, {target}> const &g, long n_iw) {{ return make_gf_imfreq<0>(g, n_iw); }}\n")
    f.write("\n")

    # --- make_gf_dlr_imfreq (product mesh wrappers) ---
    f.write("  // make_gf_dlr_imfreq: product mesh wrappers\n")
    for target in PROD_DLR_TARGETS:
        for gf in ["gf", "block_gf"]:
            view = GF_VIEW_TYPES[gf]
            for M in LATTICE_MESHES:
                f.write(f"  auto make_gf_dlr_imfreq({view}<prod<dlr, {M}>, {target}> g) {{ return make_gf_dlr_imfreq<0>(g); }}\n")
                f.write(f"  auto make_gf_dlr_imfreq({view}<prod<{M}, dlr>, {target}> g) {{ return make_gf_dlr_imfreq<1>(g); }}\n")
    f.write("\n")

    # --- make_gf_imfreq (product mesh wrappers) ---
    f.write("  // make_gf_imfreq: product mesh wrappers\n")
    for target in PROD_DLR_TARGETS:
        for gf in ["gf", "block_gf"]:
            view = GF_VIEW_TYPES[gf]
            for M in LATTICE_MESHES:
                f.write(f"  auto make_gf_imfreq({view}<prod<dlr, {M}>, {target}> g, long n_iw) {{ return make_gf_imfreq<0>(g, n_iw); }}\n")
                f.write(f"  auto make_gf_imfreq({view}<prod<{M}, dlr>, {target}> g, long n_iw) {{ return make_gf_imfreq<1>(g, n_iw); }}\n")
    f.write("\n")

    f.write("} // namespace triqs::gfs\n")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

MODULES = {
    "gf_factories_hermitian": (write_hermitian, "make_hermitian|make_real_in_tau|make_gf_dlr|fit_gf_dlr"),
    "gf_factories_fourier": (write_fourier, "make_gf_from_fourier"),
    "gf_factories_dlr_imtime": (write_dlr_imtime, "make_gf_dlr_imtime|make_gf_imtime"),
    "gf_factories_dlr_imfreq": (write_dlr_imfreq, "make_gf_dlr_imfreq|make_gf_imfreq"),
}

for name, (writer, match_names) in MODULES.items():
    # Generate .toml
    with open(f"{name}.toml", "w") as f:
        f.write('package_name = "triqs.gfs"\n')
        f.write('documentation = ""\n')
        f.write('namespaces = "triqs::gfs"\n')
        f.write(f'match_names = "{match_names}"\n')

    # Generate .cpp
    with open(f"{name}.cpp", "w") as f:
        f.write(f"// Generated by gf_factories.inst.py. Do not edit!\n")
        f.write("#include <c2py/c2py.hpp>\n")
        f.write("#include <nda/c2py/converters.hpp>\n")
        f.write("#include <triqs/c2py_converters/gf.hpp>\n")
        f.write("#include <triqs/c2py_converters/lattice.hpp>\n")
        f.write("#include <triqs/c2py_converters/mesh.hpp>\n")
        f.write("#include <triqs/lattice.hpp>\n")
        f.write(f'#include "./{name}.hpp"\n')

    # Generate .hpp
    with open(f"{name}.hpp", "w") as f:
        writer(f)

    print(f"Generated {name}.{{hpp,cpp,toml}}")
