// Generated by gf_factories.inst.py. Do not edit!
#pragma once

#include <triqs/gfs.hpp>
#include <triqs/gfs/functions/dlr.hpp>
#include <triqs/gfs/functions/dlr2d.hpp>
#include <triqs/gfs/functions/imfreq.hpp>
#include <triqs/gfs/transform/fourier.hpp>
#include <triqs/mesh.hpp>

using namespace triqs::arrays;
using namespace triqs::gfs;
using namespace triqs::mesh;

namespace triqs::gfs {

  // make_gf_dlr_imfreq: from dlr and dlr_imtime
  /**
   * @brief Build a DLR Matsubara Green's function from a DLR-coefficient or DLR-imaginary-time input.
   *
   * @details Applies to every overload. The input lives on a single
   * DLR coefficient mesh or DLR imaginary-time mesh, or on a product
   * mesh pairing a DLR axis with a lattice axis. Block and
   * block-of-block Green's function containers are handled
   * component-wise, and product meshes are handled axis-wise. All
   * target ranks (scalar, vector, matrix, rank-3, rank-4) are
   * supported. The output lives on the DLR Matsubara frequency mesh
   * associated with the input's DLR grid.
   *
   * @param g A Green's function on a DLR coefficient or DLR imaginary-time mesh.
   * @return The Green's function evaluated on the DLR Matsubara frequency mesh.
   */
  auto make_gf_dlr_imfreq(gf_const_view<dlr, scalar_valued> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(gf_const_view<dlr_imtime, scalar_valued> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block_gf_const_view<dlr, scalar_valued> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block_gf_const_view<dlr_imtime, scalar_valued> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block2_gf_const_view<dlr, scalar_valued> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block2_gf_const_view<dlr_imtime, scalar_valued> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(gf_const_view<dlr, tensor_valued<1>> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(gf_const_view<dlr_imtime, tensor_valued<1>> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block_gf_const_view<dlr, tensor_valued<1>> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block_gf_const_view<dlr_imtime, tensor_valued<1>> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block2_gf_const_view<dlr, tensor_valued<1>> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block2_gf_const_view<dlr_imtime, tensor_valued<1>> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(gf_const_view<dlr, matrix_valued> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(gf_const_view<dlr_imtime, matrix_valued> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block_gf_const_view<dlr, matrix_valued> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block_gf_const_view<dlr_imtime, matrix_valued> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block2_gf_const_view<dlr, matrix_valued> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block2_gf_const_view<dlr_imtime, matrix_valued> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(gf_const_view<dlr, tensor_valued<3>> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(gf_const_view<dlr_imtime, tensor_valued<3>> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block_gf_const_view<dlr, tensor_valued<3>> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block_gf_const_view<dlr_imtime, tensor_valued<3>> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block2_gf_const_view<dlr, tensor_valued<3>> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block2_gf_const_view<dlr_imtime, tensor_valued<3>> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(gf_const_view<dlr, tensor_valued<4>> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(gf_const_view<dlr_imtime, tensor_valued<4>> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block_gf_const_view<dlr, tensor_valued<4>> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block_gf_const_view<dlr_imtime, tensor_valued<4>> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block2_gf_const_view<dlr, tensor_valued<4>> const &g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block2_gf_const_view<dlr_imtime, tensor_valued<4>> const &g) { return make_gf_dlr_imfreq<0>(g); }

  // make_gf_imfreq: from dlr, dlr_imtime, dlr_imfreq
  /**
   * @brief Build a uniform Matsubara Green's function from any DLR representation.
   *
   * @details Applies to every overload. The input lives on a single
   * DLR coefficient, DLR imaginary-time, or DLR Matsubara frequency
   * mesh, or on a product mesh pairing a DLR axis with a lattice
   * axis. Block and block-of-block Green's function containers are
   * handled component-wise, and product meshes are handled axis-wise.
   * All target ranks (scalar, vector, matrix, rank-3, rank-4) are
   * supported. Inputs on a DLR imaginary-time or DLR Matsubara
   * frequency mesh are first converted to DLR coefficients
   * internally.
   *
   * @param g A Green's function on a DLR coefficient, DLR imaginary-time, or DLR Matsubara frequency mesh.
   * @param n_iw Number of positive Matsubara frequencies in the output mesh.
   * @return The Green's function on a uniform Matsubara frequency mesh.
   */
  auto make_gf_imfreq(gf_const_view<dlr, scalar_valued> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<dlr_imtime, scalar_valued> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<dlr_imfreq, scalar_valued> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<dlr, scalar_valued> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<dlr_imtime, scalar_valued> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<dlr_imfreq, scalar_valued> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block2_gf_const_view<dlr, scalar_valued> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block2_gf_const_view<dlr_imtime, scalar_valued> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block2_gf_const_view<dlr_imfreq, scalar_valued> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<dlr, tensor_valued<1>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<dlr_imtime, tensor_valued<1>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<dlr_imfreq, tensor_valued<1>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<dlr, tensor_valued<1>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<dlr_imtime, tensor_valued<1>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<dlr_imfreq, tensor_valued<1>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block2_gf_const_view<dlr, tensor_valued<1>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block2_gf_const_view<dlr_imtime, tensor_valued<1>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block2_gf_const_view<dlr_imfreq, tensor_valued<1>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<dlr, matrix_valued> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<dlr_imtime, matrix_valued> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<dlr_imfreq, matrix_valued> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<dlr, matrix_valued> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<dlr_imtime, matrix_valued> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<dlr_imfreq, matrix_valued> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block2_gf_const_view<dlr, matrix_valued> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block2_gf_const_view<dlr_imtime, matrix_valued> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block2_gf_const_view<dlr_imfreq, matrix_valued> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<dlr, tensor_valued<3>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<dlr_imtime, tensor_valued<3>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<dlr_imfreq, tensor_valued<3>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<dlr, tensor_valued<3>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<dlr_imtime, tensor_valued<3>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<dlr_imfreq, tensor_valued<3>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block2_gf_const_view<dlr, tensor_valued<3>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block2_gf_const_view<dlr_imtime, tensor_valued<3>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block2_gf_const_view<dlr_imfreq, tensor_valued<3>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<dlr, tensor_valued<4>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<dlr_imtime, tensor_valued<4>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<dlr_imfreq, tensor_valued<4>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<dlr, tensor_valued<4>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<dlr_imtime, tensor_valued<4>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<dlr_imfreq, tensor_valued<4>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block2_gf_const_view<dlr, tensor_valued<4>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block2_gf_const_view<dlr_imtime, tensor_valued<4>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block2_gf_const_view<dlr_imfreq, tensor_valued<4>> const &g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }

  // make_gf_dlr_imfreq: sample an imfreq Gf onto a DLR imfreq mesh
  auto make_gf_dlr_imfreq(gf_const_view<imfreq, scalar_valued> const &g, double w_max, double eps, bool symmetrize = true) { return make_gf_dlr_imfreq<0>(g, w_max, eps, symmetrize); }
  auto make_gf_dlr_imfreq(block_gf_const_view<imfreq, scalar_valued> const &g, double w_max, double eps, bool symmetrize = true) { return make_gf_dlr_imfreq<0>(g, w_max, eps, symmetrize); }
  auto make_gf_dlr_imfreq(gf_const_view<imfreq, tensor_valued<1>> const &g, double w_max, double eps, bool symmetrize = true) { return make_gf_dlr_imfreq<0>(g, w_max, eps, symmetrize); }
  auto make_gf_dlr_imfreq(block_gf_const_view<imfreq, tensor_valued<1>> const &g, double w_max, double eps, bool symmetrize = true) { return make_gf_dlr_imfreq<0>(g, w_max, eps, symmetrize); }
  auto make_gf_dlr_imfreq(gf_const_view<imfreq, matrix_valued> const &g, double w_max, double eps, bool symmetrize = true) { return make_gf_dlr_imfreq<0>(g, w_max, eps, symmetrize); }
  auto make_gf_dlr_imfreq(block_gf_const_view<imfreq, matrix_valued> const &g, double w_max, double eps, bool symmetrize = true) { return make_gf_dlr_imfreq<0>(g, w_max, eps, symmetrize); }
  auto make_gf_dlr_imfreq(gf_const_view<imfreq, tensor_valued<3>> const &g, double w_max, double eps, bool symmetrize = true) { return make_gf_dlr_imfreq<0>(g, w_max, eps, symmetrize); }
  auto make_gf_dlr_imfreq(block_gf_const_view<imfreq, tensor_valued<3>> const &g, double w_max, double eps, bool symmetrize = true) { return make_gf_dlr_imfreq<0>(g, w_max, eps, symmetrize); }
  auto make_gf_dlr_imfreq(gf_const_view<imfreq, tensor_valued<4>> const &g, double w_max, double eps, bool symmetrize = true) { return make_gf_dlr_imfreq<0>(g, w_max, eps, symmetrize); }
  auto make_gf_dlr_imfreq(block_gf_const_view<imfreq, tensor_valued<4>> const &g, double w_max, double eps, bool symmetrize = true) { return make_gf_dlr_imfreq<0>(g, w_max, eps, symmetrize); }

  // find_w_max: smallest DLR cutoff w_max with round-trip error < eps for an imfreq Gf
  /**
   * @brief Find the smallest DLR energy cutoff that reproduces a Matsubara Green's function within a target accuracy.
   *
   * @details Applies to every overload. Starting from ``w_max_init``, the
   * cutoff is grown by a factor of 1.5 per iteration. For each
   * candidate cutoff, the function builds a DLR Matsubara mesh from
   * (``w_max``, ``eps``, ``symmetrize``), samples ``g`` on that DLR mesh, reconstructs
   * the Green's function on the original Matsubara mesh via the DLR
   * coefficients, and measures the worst-case round-trip error across
   * Matsubara indices and target indices. The smallest ``w_max`` not
   * exceeding ``w_max_max`` whose round-trip error is below ``eps`` is
   * returned.
   *
   * Candidate cutoffs whose DLR frequency range exceeds the Matsubara
   * range of the input are skipped. For a block Green's function, the
   * reported per-iteration error is the worst case across all blocks.
   * An exception is raised if ``w_max_init`` exceeds ``w_max_max``, or if no
   * candidate cutoff up to ``w_max_max`` achieves an error below ``eps``.
   *
   * @param g Input Green's function on a Matsubara frequency mesh.
   * @param eps Target DLR accuracy and round-trip error tolerance.
   * @param symmetrize If `true`, use particle-hole symmetric DLR meshes.
   * @param w_max_init Initial value of the DLR cutoff to try (must not exceed ``w_max_max``).
   * @param w_max_max Maximum DLR cutoff to try before giving up.
   * @return The smallest ``w_max`` not exceeding ``w_max_max`` for which the round-trip error is below ``eps``.
   */
  double find_w_max(gf_const_view<imfreq, scalar_valued> const &g, double eps = 1e-10, bool symmetrize = true, double w_max_init = 1.0, double w_max_max = 200.0) { return find_w_max<0>(g, eps, symmetrize, w_max_init, w_max_max); }
  double find_w_max(block_gf_const_view<imfreq, scalar_valued> const &g, double eps = 1e-10, bool symmetrize = true, double w_max_init = 1.0, double w_max_max = 200.0) { return find_w_max<0>(g, eps, symmetrize, w_max_init, w_max_max); }
  double find_w_max(gf_const_view<imfreq, tensor_valued<1>> const &g, double eps = 1e-10, bool symmetrize = true, double w_max_init = 1.0, double w_max_max = 200.0) { return find_w_max<0>(g, eps, symmetrize, w_max_init, w_max_max); }
  double find_w_max(block_gf_const_view<imfreq, tensor_valued<1>> const &g, double eps = 1e-10, bool symmetrize = true, double w_max_init = 1.0, double w_max_max = 200.0) { return find_w_max<0>(g, eps, symmetrize, w_max_init, w_max_max); }
  double find_w_max(gf_const_view<imfreq, matrix_valued> const &g, double eps = 1e-10, bool symmetrize = true, double w_max_init = 1.0, double w_max_max = 200.0) { return find_w_max<0>(g, eps, symmetrize, w_max_init, w_max_max); }
  double find_w_max(block_gf_const_view<imfreq, matrix_valued> const &g, double eps = 1e-10, bool symmetrize = true, double w_max_init = 1.0, double w_max_max = 200.0) { return find_w_max<0>(g, eps, symmetrize, w_max_init, w_max_max); }
  double find_w_max(gf_const_view<imfreq, tensor_valued<3>> const &g, double eps = 1e-10, bool symmetrize = true, double w_max_init = 1.0, double w_max_max = 200.0) { return find_w_max<0>(g, eps, symmetrize, w_max_init, w_max_max); }
  double find_w_max(block_gf_const_view<imfreq, tensor_valued<3>> const &g, double eps = 1e-10, bool symmetrize = true, double w_max_init = 1.0, double w_max_max = 200.0) { return find_w_max<0>(g, eps, symmetrize, w_max_init, w_max_max); }
  double find_w_max(gf_const_view<imfreq, tensor_valued<4>> const &g, double eps = 1e-10, bool symmetrize = true, double w_max_init = 1.0, double w_max_max = 200.0) { return find_w_max<0>(g, eps, symmetrize, w_max_init, w_max_max); }
  double find_w_max(block_gf_const_view<imfreq, tensor_valued<4>> const &g, double eps = 1e-10, bool symmetrize = true, double w_max_init = 1.0, double w_max_max = 200.0) { return find_w_max<0>(g, eps, symmetrize, w_max_init, w_max_max); }

  // make_gf_dlr_imfreq: product mesh wrappers
  auto make_gf_dlr_imfreq(gf_const_view<prod<dlr, brzone>, scalar_valued> g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(gf_const_view<prod<brzone, dlr>, scalar_valued> g) { return make_gf_dlr_imfreq<1>(g); }
  auto make_gf_dlr_imfreq(gf_const_view<prod<dlr, cyclat>, scalar_valued> g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(gf_const_view<prod<cyclat, dlr>, scalar_valued> g) { return make_gf_dlr_imfreq<1>(g); }
  auto make_gf_dlr_imfreq(block_gf_const_view<prod<dlr, brzone>, scalar_valued> g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block_gf_const_view<prod<brzone, dlr>, scalar_valued> g) { return make_gf_dlr_imfreq<1>(g); }
  auto make_gf_dlr_imfreq(block_gf_const_view<prod<dlr, cyclat>, scalar_valued> g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block_gf_const_view<prod<cyclat, dlr>, scalar_valued> g) { return make_gf_dlr_imfreq<1>(g); }
  auto make_gf_dlr_imfreq(gf_const_view<prod<dlr, brzone>, matrix_valued> g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(gf_const_view<prod<brzone, dlr>, matrix_valued> g) { return make_gf_dlr_imfreq<1>(g); }
  auto make_gf_dlr_imfreq(gf_const_view<prod<dlr, cyclat>, matrix_valued> g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(gf_const_view<prod<cyclat, dlr>, matrix_valued> g) { return make_gf_dlr_imfreq<1>(g); }
  auto make_gf_dlr_imfreq(block_gf_const_view<prod<dlr, brzone>, matrix_valued> g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block_gf_const_view<prod<brzone, dlr>, matrix_valued> g) { return make_gf_dlr_imfreq<1>(g); }
  auto make_gf_dlr_imfreq(block_gf_const_view<prod<dlr, cyclat>, matrix_valued> g) { return make_gf_dlr_imfreq<0>(g); }
  auto make_gf_dlr_imfreq(block_gf_const_view<prod<cyclat, dlr>, matrix_valued> g) { return make_gf_dlr_imfreq<1>(g); }

  // make_gf_imfreq: product mesh wrappers
  auto make_gf_imfreq(gf_const_view<prod<dlr, brzone>, scalar_valued> g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<prod<brzone, dlr>, scalar_valued> g, long n_iw) { return make_gf_imfreq<1>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<prod<dlr, cyclat>, scalar_valued> g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<prod<cyclat, dlr>, scalar_valued> g, long n_iw) { return make_gf_imfreq<1>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<prod<dlr, brzone>, scalar_valued> g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<prod<brzone, dlr>, scalar_valued> g, long n_iw) { return make_gf_imfreq<1>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<prod<dlr, cyclat>, scalar_valued> g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<prod<cyclat, dlr>, scalar_valued> g, long n_iw) { return make_gf_imfreq<1>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<prod<dlr, brzone>, matrix_valued> g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<prod<brzone, dlr>, matrix_valued> g, long n_iw) { return make_gf_imfreq<1>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<prod<dlr, cyclat>, matrix_valued> g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<prod<cyclat, dlr>, matrix_valued> g, long n_iw) { return make_gf_imfreq<1>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<prod<dlr, brzone>, matrix_valued> g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<prod<brzone, dlr>, matrix_valued> g, long n_iw) { return make_gf_imfreq<1>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<prod<dlr, cyclat>, matrix_valued> g, long n_iw) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<prod<cyclat, dlr>, matrix_valued> g, long n_iw) { return make_gf_imfreq<1>(g, n_iw); }

  // make_gf_imfreq: dlr2d -> prod<imfreq, imfreq>
  auto make_gf_imfreq(gf_const_view<dlr2d, scalar_valued> const &g, long n_iw = 0) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<dlr2d, scalar_valued> const &g, long n_iw = 0) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block2_gf_const_view<dlr2d, scalar_valued> const &g, long n_iw = 0) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<dlr2d, tensor_valued<1>> const &g, long n_iw = 0) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<dlr2d, tensor_valued<1>> const &g, long n_iw = 0) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block2_gf_const_view<dlr2d, tensor_valued<1>> const &g, long n_iw = 0) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<dlr2d, matrix_valued> const &g, long n_iw = 0) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<dlr2d, matrix_valued> const &g, long n_iw = 0) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block2_gf_const_view<dlr2d, matrix_valued> const &g, long n_iw = 0) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<dlr2d, tensor_valued<3>> const &g, long n_iw = 0) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<dlr2d, tensor_valued<3>> const &g, long n_iw = 0) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block2_gf_const_view<dlr2d, tensor_valued<3>> const &g, long n_iw = 0) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(gf_const_view<dlr2d, tensor_valued<4>> const &g, long n_iw = 0) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block_gf_const_view<dlr2d, tensor_valued<4>> const &g, long n_iw = 0) { return make_gf_imfreq<0>(g, n_iw); }
  auto make_gf_imfreq(block2_gf_const_view<dlr2d, tensor_valued<4>> const &g, long n_iw = 0) { return make_gf_imfreq<0>(g, n_iw); }

} // namespace triqs::gfs
