// Generated by gf_factories.inst.py. Do not edit!
#include <c2py/c2py.hpp>
#include <nda/c2py/converters.hpp>
#include <triqs/c2py_converters/gf.hpp>
#include <triqs/c2py_converters/lattice.hpp>
#include <triqs/c2py_converters/mesh.hpp>
#include <triqs/lattice.hpp>
#include "./gf_factories_dlr_imfreq.hpp"

#include "gf_factories_dlr_imfreq.wrap.cxx"
