// Generated by gf_factories.inst.py. Do not edit!
#pragma once

#include <triqs/gfs.hpp>
#include <triqs/gfs/functions/dlr.hpp>
#include <triqs/gfs/functions/imfreq.hpp>
#include <triqs/gfs/transform/fourier.hpp>
#include <triqs/mesh.hpp>

using namespace triqs::arrays;
using namespace triqs::gfs;
using namespace triqs::mesh;

namespace triqs::gfs {

  // === scalar_valued (rank 0) ===

  // imtime -> imfreq
  template gf<imfreq, scalar_valued> make_gf_from_fourier(gf_const_view<imtime, scalar_valued>, int);
  template gf<imfreq, scalar_valued> make_gf_from_fourier(gf_const_view<imtime, scalar_real_valued>, int);
  /**
   * @brief Build a Green's function on the conjugate mesh by Fourier transform.
   *
   * @details Applies to every overload. The supported conjugate mesh
   * pairs are imaginary time and Matsubara frequencies, real time and
   * real frequency, cyclic lattice and Brillouin zone, and DLR
   * imaginary time and DLR Matsubara frequencies. Product meshes
   * pairing one of these Fourier axes with a lattice axis, as well as
   * block and block-of-block Green's function containers, are
   * transformed block- and component-wise. All target ranks (scalar,
   * vector, matrix, rank-3, rank-4) are supported.
   *
   * Beyond the input Green's function, the following optional
   * positional arguments may be passed; which one applies depends on
   * the input mesh.
   *
   *   - ``n_iw``: the number of positive Matsubara frequencies in
   *     the output mesh, when the input lives on imaginary time
   *     (default is -1, which selects the default size from the input).
   *   - ``n_tau``: the number of imaginary-time points in the output
   *     mesh, when the input lives on Matsubara frequencies
   *     (default is -1, which selects the default size from the input).
   *   - ``shift_half_bin``: a half-bin shift flag for the output
   *     mesh, for the real-time and real-frequency pair (default is false).
   *   - ``mesh`` and ``known_moments``: an explicit output mesh
   *     together with an array of high-frequency moments, for the
   *     imaginary-time and Matsubara and the real-time and
   *     real-frequency pairs. The known-moment tail correction
   *     improves accuracy at high frequency.
   *
   * @param g The input Green's function.
   * @return A new Green's function on the conjugate mesh.
   */
  auto make_gf_from_fourier(block_gf_const_view<imtime, scalar_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, scalar_real_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, scalar_valued> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, scalar_real_valued> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, scalar_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, scalar_real_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, scalar_valued> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, scalar_real_valued> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }

  // imfreq -> imtime
  template gf<imtime, scalar_valued> make_gf_from_fourier(gf_const_view<imfreq, scalar_valued>, int);
  auto make_gf_from_fourier(block_gf_const_view<imfreq, scalar_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<imfreq, scalar_valued> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<imfreq, scalar_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<imfreq, scalar_valued> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }

  // retime -> refreq
  template gf<refreq, scalar_valued> make_gf_from_fourier(gf_const_view<retime, scalar_valued>, bool);
  template gf<refreq, scalar_valued> make_gf_from_fourier(gf_const_view<retime, scalar_real_valued>, bool);
  auto make_gf_from_fourier(block_gf_const_view<retime, scalar_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<retime, scalar_real_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<retime, scalar_valued> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block_gf_const_view<retime, scalar_real_valued> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, scalar_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, scalar_real_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, scalar_valued> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, scalar_real_valued> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }

  // refreq -> retime
  template gf<retime, scalar_valued> make_gf_from_fourier(gf_const_view<refreq, scalar_valued>, bool);
  auto make_gf_from_fourier(block_gf_const_view<refreq, scalar_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<refreq, scalar_valued> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<refreq, scalar_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<refreq, scalar_valued> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }

  // Known moments
  auto make_gf_from_fourier(gf_const_view<imtime, scalar_valued> g, imfreq const &m, array_const_view<dcomplex, 1> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<imtime, scalar_real_valued> g, imfreq const &m, array_const_view<dcomplex, 1> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, scalar_valued> const &g, imfreq const &m, std::vector<array<dcomplex, 1>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, scalar_real_valued> const &g, imfreq const &m, std::vector<array<dcomplex, 1>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, scalar_valued> const &g, imfreq const &m, std::vector<std::vector<array<dcomplex, 1>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, scalar_real_valued> const &g, imfreq const &m, std::vector<std::vector<array<dcomplex, 1>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<imfreq, scalar_valued> g, imtime const &m, array_const_view<dcomplex, 1> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<imfreq, scalar_valued> const &g, imtime const &m, std::vector<array<dcomplex, 1>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<imfreq, scalar_valued> const &g, imtime const &m, std::vector<std::vector<array<dcomplex, 1>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<retime, scalar_valued> g, refreq const &m, array_const_view<dcomplex, 1> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<retime, scalar_real_valued> g, refreq const &m, array_const_view<dcomplex, 1> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<retime, scalar_valued> const &g, refreq const &m, std::vector<array<dcomplex, 1>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<retime, scalar_real_valued> const &g, refreq const &m, std::vector<array<dcomplex, 1>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, scalar_valued> const &g, refreq const &m, std::vector<std::vector<array<dcomplex, 1>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, scalar_real_valued> const &g, refreq const &m, std::vector<std::vector<array<dcomplex, 1>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<refreq, scalar_valued> g, retime const &m, array_const_view<dcomplex, 1> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<refreq, scalar_valued> const &g, retime const &m, std::vector<array<dcomplex, 1>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<refreq, scalar_valued> const &g, retime const &m, std::vector<std::vector<array<dcomplex, 1>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }

  // Lattice Fourier
  auto make_gf_from_fourier(gf_const_view<brzone, scalar_valued> g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<brzone, scalar_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<brzone, scalar_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(gf_const_view<cyclat, scalar_valued> g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<cyclat, scalar_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<cyclat, scalar_valued> const &g) { return make_gf_from_fourier<0>(g); }

  // === tensor_valued<1> (rank 1) ===

  // imtime -> imfreq
  template gf<imfreq, tensor_valued<1>> make_gf_from_fourier(gf_const_view<imtime, tensor_valued<1>>, int);
  template gf<imfreq, tensor_valued<1>> make_gf_from_fourier(gf_const_view<imtime, tensor_real_valued<1>>, int);
  auto make_gf_from_fourier(block_gf_const_view<imtime, tensor_valued<1>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, tensor_real_valued<1>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, tensor_valued<1>> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, tensor_real_valued<1>> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, tensor_valued<1>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, tensor_real_valued<1>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, tensor_valued<1>> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, tensor_real_valued<1>> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }

  // imfreq -> imtime
  template gf<imtime, tensor_valued<1>> make_gf_from_fourier(gf_const_view<imfreq, tensor_valued<1>>, int);
  auto make_gf_from_fourier(block_gf_const_view<imfreq, tensor_valued<1>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<imfreq, tensor_valued<1>> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<imfreq, tensor_valued<1>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<imfreq, tensor_valued<1>> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }

  // retime -> refreq
  template gf<refreq, tensor_valued<1>> make_gf_from_fourier(gf_const_view<retime, tensor_valued<1>>, bool);
  template gf<refreq, tensor_valued<1>> make_gf_from_fourier(gf_const_view<retime, tensor_real_valued<1>>, bool);
  auto make_gf_from_fourier(block_gf_const_view<retime, tensor_valued<1>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<retime, tensor_real_valued<1>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<retime, tensor_valued<1>> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block_gf_const_view<retime, tensor_real_valued<1>> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, tensor_valued<1>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, tensor_real_valued<1>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, tensor_valued<1>> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, tensor_real_valued<1>> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }

  // refreq -> retime
  template gf<retime, tensor_valued<1>> make_gf_from_fourier(gf_const_view<refreq, tensor_valued<1>>, bool);
  auto make_gf_from_fourier(block_gf_const_view<refreq, tensor_valued<1>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<refreq, tensor_valued<1>> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<refreq, tensor_valued<1>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<refreq, tensor_valued<1>> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }

  // Known moments
  auto make_gf_from_fourier(gf_const_view<imtime, tensor_valued<1>> g, imfreq const &m, array_const_view<dcomplex, 2> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<imtime, tensor_real_valued<1>> g, imfreq const &m, array_const_view<dcomplex, 2> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, tensor_valued<1>> const &g, imfreq const &m, std::vector<array<dcomplex, 2>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, tensor_real_valued<1>> const &g, imfreq const &m, std::vector<array<dcomplex, 2>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, tensor_valued<1>> const &g, imfreq const &m, std::vector<std::vector<array<dcomplex, 2>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, tensor_real_valued<1>> const &g, imfreq const &m, std::vector<std::vector<array<dcomplex, 2>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<imfreq, tensor_valued<1>> g, imtime const &m, array_const_view<dcomplex, 2> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<imfreq, tensor_valued<1>> const &g, imtime const &m, std::vector<array<dcomplex, 2>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<imfreq, tensor_valued<1>> const &g, imtime const &m, std::vector<std::vector<array<dcomplex, 2>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<retime, tensor_valued<1>> g, refreq const &m, array_const_view<dcomplex, 2> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<retime, tensor_real_valued<1>> g, refreq const &m, array_const_view<dcomplex, 2> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<retime, tensor_valued<1>> const &g, refreq const &m, std::vector<array<dcomplex, 2>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<retime, tensor_real_valued<1>> const &g, refreq const &m, std::vector<array<dcomplex, 2>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, tensor_valued<1>> const &g, refreq const &m, std::vector<std::vector<array<dcomplex, 2>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, tensor_real_valued<1>> const &g, refreq const &m, std::vector<std::vector<array<dcomplex, 2>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<refreq, tensor_valued<1>> g, retime const &m, array_const_view<dcomplex, 2> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<refreq, tensor_valued<1>> const &g, retime const &m, std::vector<array<dcomplex, 2>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<refreq, tensor_valued<1>> const &g, retime const &m, std::vector<std::vector<array<dcomplex, 2>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }

  // Lattice Fourier
  auto make_gf_from_fourier(gf_const_view<brzone, tensor_valued<1>> g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<brzone, tensor_valued<1>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<brzone, tensor_valued<1>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(gf_const_view<cyclat, tensor_valued<1>> g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<cyclat, tensor_valued<1>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<cyclat, tensor_valued<1>> const &g) { return make_gf_from_fourier<0>(g); }

  // === matrix_valued (rank 2) ===

  // imtime -> imfreq
  template gf<imfreq, matrix_valued> make_gf_from_fourier(gf_const_view<imtime, matrix_valued>, int);
  template gf<imfreq, matrix_valued> make_gf_from_fourier(gf_const_view<imtime, matrix_real_valued>, int);
  auto make_gf_from_fourier(block_gf_const_view<imtime, matrix_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, matrix_real_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, matrix_valued> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, matrix_real_valued> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, matrix_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, matrix_real_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, matrix_valued> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, matrix_real_valued> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }

  // imfreq -> imtime
  template gf<imtime, matrix_valued> make_gf_from_fourier(gf_const_view<imfreq, matrix_valued>, int);
  auto make_gf_from_fourier(block_gf_const_view<imfreq, matrix_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<imfreq, matrix_valued> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<imfreq, matrix_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<imfreq, matrix_valued> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }

  // retime -> refreq
  template gf<refreq, matrix_valued> make_gf_from_fourier(gf_const_view<retime, matrix_valued>, bool);
  template gf<refreq, matrix_valued> make_gf_from_fourier(gf_const_view<retime, matrix_real_valued>, bool);
  auto make_gf_from_fourier(block_gf_const_view<retime, matrix_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<retime, matrix_real_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<retime, matrix_valued> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block_gf_const_view<retime, matrix_real_valued> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, matrix_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, matrix_real_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, matrix_valued> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, matrix_real_valued> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }

  // refreq -> retime
  template gf<retime, matrix_valued> make_gf_from_fourier(gf_const_view<refreq, matrix_valued>, bool);
  auto make_gf_from_fourier(block_gf_const_view<refreq, matrix_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<refreq, matrix_valued> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<refreq, matrix_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<refreq, matrix_valued> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }

  // Known moments
  auto make_gf_from_fourier(gf_const_view<imtime, matrix_valued> g, imfreq const &m, array_const_view<dcomplex, 3> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<imtime, matrix_real_valued> g, imfreq const &m, array_const_view<dcomplex, 3> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, matrix_valued> const &g, imfreq const &m, std::vector<array<dcomplex, 3>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, matrix_real_valued> const &g, imfreq const &m, std::vector<array<dcomplex, 3>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, matrix_valued> const &g, imfreq const &m, std::vector<std::vector<array<dcomplex, 3>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, matrix_real_valued> const &g, imfreq const &m, std::vector<std::vector<array<dcomplex, 3>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<imfreq, matrix_valued> g, imtime const &m, array_const_view<dcomplex, 3> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<imfreq, matrix_valued> const &g, imtime const &m, std::vector<array<dcomplex, 3>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<imfreq, matrix_valued> const &g, imtime const &m, std::vector<std::vector<array<dcomplex, 3>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<retime, matrix_valued> g, refreq const &m, array_const_view<dcomplex, 3> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<retime, matrix_real_valued> g, refreq const &m, array_const_view<dcomplex, 3> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<retime, matrix_valued> const &g, refreq const &m, std::vector<array<dcomplex, 3>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<retime, matrix_real_valued> const &g, refreq const &m, std::vector<array<dcomplex, 3>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, matrix_valued> const &g, refreq const &m, std::vector<std::vector<array<dcomplex, 3>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, matrix_real_valued> const &g, refreq const &m, std::vector<std::vector<array<dcomplex, 3>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<refreq, matrix_valued> g, retime const &m, array_const_view<dcomplex, 3> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<refreq, matrix_valued> const &g, retime const &m, std::vector<array<dcomplex, 3>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<refreq, matrix_valued> const &g, retime const &m, std::vector<std::vector<array<dcomplex, 3>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }

  // Lattice Fourier
  auto make_gf_from_fourier(gf_const_view<brzone, matrix_valued> g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<brzone, matrix_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<brzone, matrix_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(gf_const_view<cyclat, matrix_valued> g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<cyclat, matrix_valued> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<cyclat, matrix_valued> const &g) { return make_gf_from_fourier<0>(g); }

  // === tensor_valued<3> (rank 3) ===

  // imtime -> imfreq
  template gf<imfreq, tensor_valued<3>> make_gf_from_fourier(gf_const_view<imtime, tensor_valued<3>>, int);
  template gf<imfreq, tensor_valued<3>> make_gf_from_fourier(gf_const_view<imtime, tensor_real_valued<3>>, int);
  auto make_gf_from_fourier(block_gf_const_view<imtime, tensor_valued<3>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, tensor_real_valued<3>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, tensor_valued<3>> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, tensor_real_valued<3>> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, tensor_valued<3>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, tensor_real_valued<3>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, tensor_valued<3>> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, tensor_real_valued<3>> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }

  // imfreq -> imtime
  template gf<imtime, tensor_valued<3>> make_gf_from_fourier(gf_const_view<imfreq, tensor_valued<3>>, int);
  auto make_gf_from_fourier(block_gf_const_view<imfreq, tensor_valued<3>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<imfreq, tensor_valued<3>> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<imfreq, tensor_valued<3>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<imfreq, tensor_valued<3>> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }

  // retime -> refreq
  template gf<refreq, tensor_valued<3>> make_gf_from_fourier(gf_const_view<retime, tensor_valued<3>>, bool);
  template gf<refreq, tensor_valued<3>> make_gf_from_fourier(gf_const_view<retime, tensor_real_valued<3>>, bool);
  auto make_gf_from_fourier(block_gf_const_view<retime, tensor_valued<3>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<retime, tensor_real_valued<3>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<retime, tensor_valued<3>> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block_gf_const_view<retime, tensor_real_valued<3>> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, tensor_valued<3>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, tensor_real_valued<3>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, tensor_valued<3>> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, tensor_real_valued<3>> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }

  // refreq -> retime
  template gf<retime, tensor_valued<3>> make_gf_from_fourier(gf_const_view<refreq, tensor_valued<3>>, bool);
  auto make_gf_from_fourier(block_gf_const_view<refreq, tensor_valued<3>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<refreq, tensor_valued<3>> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<refreq, tensor_valued<3>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<refreq, tensor_valued<3>> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }

  // Known moments
  auto make_gf_from_fourier(gf_const_view<imtime, tensor_valued<3>> g, imfreq const &m, array_const_view<dcomplex, 4> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<imtime, tensor_real_valued<3>> g, imfreq const &m, array_const_view<dcomplex, 4> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, tensor_valued<3>> const &g, imfreq const &m, std::vector<array<dcomplex, 4>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, tensor_real_valued<3>> const &g, imfreq const &m, std::vector<array<dcomplex, 4>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, tensor_valued<3>> const &g, imfreq const &m, std::vector<std::vector<array<dcomplex, 4>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, tensor_real_valued<3>> const &g, imfreq const &m, std::vector<std::vector<array<dcomplex, 4>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<imfreq, tensor_valued<3>> g, imtime const &m, array_const_view<dcomplex, 4> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<imfreq, tensor_valued<3>> const &g, imtime const &m, std::vector<array<dcomplex, 4>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<imfreq, tensor_valued<3>> const &g, imtime const &m, std::vector<std::vector<array<dcomplex, 4>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<retime, tensor_valued<3>> g, refreq const &m, array_const_view<dcomplex, 4> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<retime, tensor_real_valued<3>> g, refreq const &m, array_const_view<dcomplex, 4> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<retime, tensor_valued<3>> const &g, refreq const &m, std::vector<array<dcomplex, 4>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<retime, tensor_real_valued<3>> const &g, refreq const &m, std::vector<array<dcomplex, 4>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, tensor_valued<3>> const &g, refreq const &m, std::vector<std::vector<array<dcomplex, 4>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, tensor_real_valued<3>> const &g, refreq const &m, std::vector<std::vector<array<dcomplex, 4>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<refreq, tensor_valued<3>> g, retime const &m, array_const_view<dcomplex, 4> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<refreq, tensor_valued<3>> const &g, retime const &m, std::vector<array<dcomplex, 4>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<refreq, tensor_valued<3>> const &g, retime const &m, std::vector<std::vector<array<dcomplex, 4>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }

  // Lattice Fourier
  auto make_gf_from_fourier(gf_const_view<brzone, tensor_valued<3>> g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<brzone, tensor_valued<3>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<brzone, tensor_valued<3>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(gf_const_view<cyclat, tensor_valued<3>> g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<cyclat, tensor_valued<3>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<cyclat, tensor_valued<3>> const &g) { return make_gf_from_fourier<0>(g); }

  // === tensor_valued<4> (rank 4) ===

  // imtime -> imfreq
  template gf<imfreq, tensor_valued<4>> make_gf_from_fourier(gf_const_view<imtime, tensor_valued<4>>, int);
  template gf<imfreq, tensor_valued<4>> make_gf_from_fourier(gf_const_view<imtime, tensor_real_valued<4>>, int);
  auto make_gf_from_fourier(block_gf_const_view<imtime, tensor_valued<4>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, tensor_real_valued<4>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, tensor_valued<4>> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, tensor_real_valued<4>> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, tensor_valued<4>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, tensor_real_valued<4>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, tensor_valued<4>> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, tensor_real_valued<4>> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }

  // imfreq -> imtime
  template gf<imtime, tensor_valued<4>> make_gf_from_fourier(gf_const_view<imfreq, tensor_valued<4>>, int);
  auto make_gf_from_fourier(block_gf_const_view<imfreq, tensor_valued<4>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<imfreq, tensor_valued<4>> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<imfreq, tensor_valued<4>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<imfreq, tensor_valued<4>> const &g, int const &x) { return make_gf_from_fourier<0>(g, x); }

  // retime -> refreq
  template gf<refreq, tensor_valued<4>> make_gf_from_fourier(gf_const_view<retime, tensor_valued<4>>, bool);
  template gf<refreq, tensor_valued<4>> make_gf_from_fourier(gf_const_view<retime, tensor_real_valued<4>>, bool);
  auto make_gf_from_fourier(block_gf_const_view<retime, tensor_valued<4>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<retime, tensor_real_valued<4>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<retime, tensor_valued<4>> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block_gf_const_view<retime, tensor_real_valued<4>> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, tensor_valued<4>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, tensor_real_valued<4>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, tensor_valued<4>> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, tensor_real_valued<4>> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }

  // refreq -> retime
  template gf<retime, tensor_valued<4>> make_gf_from_fourier(gf_const_view<refreq, tensor_valued<4>>, bool);
  auto make_gf_from_fourier(block_gf_const_view<refreq, tensor_valued<4>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<refreq, tensor_valued<4>> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }
  auto make_gf_from_fourier(block2_gf_const_view<refreq, tensor_valued<4>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<refreq, tensor_valued<4>> const &g, bool const &x) { return make_gf_from_fourier<0>(g, x); }

  // Known moments
  auto make_gf_from_fourier(gf_const_view<imtime, tensor_valued<4>> g, imfreq const &m, array_const_view<dcomplex, 5> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<imtime, tensor_real_valued<4>> g, imfreq const &m, array_const_view<dcomplex, 5> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, tensor_valued<4>> const &g, imfreq const &m, std::vector<array<dcomplex, 5>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<imtime, tensor_real_valued<4>> const &g, imfreq const &m, std::vector<array<dcomplex, 5>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, tensor_valued<4>> const &g, imfreq const &m, std::vector<std::vector<array<dcomplex, 5>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<imtime, tensor_real_valued<4>> const &g, imfreq const &m, std::vector<std::vector<array<dcomplex, 5>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<imfreq, tensor_valued<4>> g, imtime const &m, array_const_view<dcomplex, 5> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<imfreq, tensor_valued<4>> const &g, imtime const &m, std::vector<array<dcomplex, 5>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<imfreq, tensor_valued<4>> const &g, imtime const &m, std::vector<std::vector<array<dcomplex, 5>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<retime, tensor_valued<4>> g, refreq const &m, array_const_view<dcomplex, 5> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<retime, tensor_real_valued<4>> g, refreq const &m, array_const_view<dcomplex, 5> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<retime, tensor_valued<4>> const &g, refreq const &m, std::vector<array<dcomplex, 5>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<retime, tensor_real_valued<4>> const &g, refreq const &m, std::vector<array<dcomplex, 5>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, tensor_valued<4>> const &g, refreq const &m, std::vector<std::vector<array<dcomplex, 5>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<retime, tensor_real_valued<4>> const &g, refreq const &m, std::vector<std::vector<array<dcomplex, 5>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(gf_const_view<refreq, tensor_valued<4>> g, retime const &m, array_const_view<dcomplex, 5> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block_gf_const_view<refreq, tensor_valued<4>> const &g, retime const &m, std::vector<array<dcomplex, 5>> const &km) { return make_gf_from_fourier<0>(g, m, km); }
  auto make_gf_from_fourier(block2_gf_const_view<refreq, tensor_valued<4>> const &g, retime const &m, std::vector<std::vector<array<dcomplex, 5>>> const &km) { return make_gf_from_fourier<0>(g, m, km); }

  // Lattice Fourier
  auto make_gf_from_fourier(gf_const_view<brzone, tensor_valued<4>> g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<brzone, tensor_valued<4>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<brzone, tensor_valued<4>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(gf_const_view<cyclat, tensor_valued<4>> g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block_gf_const_view<cyclat, tensor_valued<4>> const &g) { return make_gf_from_fourier<0>(g); }
  auto make_gf_from_fourier(block2_gf_const_view<cyclat, tensor_valued<4>> const &g) { return make_gf_from_fourier<0>(g); }

  // Product mesh Fourier wrappers
  auto make_gf_from_fourier(gf_view<prod<brzone, dlr_imfreq>, scalar_valued> g_in) {
    return make_gf_from_fourier<0, 1>(g_in);
  }
  auto make_gf_from_fourier(block_gf_view<prod<brzone, dlr_imfreq>, scalar_valued> g_in) {
    return map_block_gf([](auto &&g_bl) { return make_gf_from_fourier<0, 1>(make_const_view(g_bl)); }, g_in);
  }
  auto make_gf_from_fourier(gf_view<prod<cyclat, dlr_imtime>, scalar_valued> g_in) {
    return make_gf_from_fourier<0, 1>(g_in);
  }
  auto make_gf_from_fourier(block_gf_view<prod<cyclat, dlr_imtime>, scalar_valued> g_in) {
    return map_block_gf([](auto &&g_bl) { return make_gf_from_fourier<0, 1>(make_const_view(g_bl)); }, g_in);
  }
  auto make_gf_from_fourier(gf_view<prod<brzone, dlr_imfreq>, matrix_valued> g_in) {
    return make_gf_from_fourier<0, 1>(g_in);
  }
  auto make_gf_from_fourier(block_gf_view<prod<brzone, dlr_imfreq>, matrix_valued> g_in) {
    return map_block_gf([](auto &&g_bl) { return make_gf_from_fourier<0, 1>(make_const_view(g_bl)); }, g_in);
  }
  auto make_gf_from_fourier(gf_view<prod<cyclat, dlr_imtime>, matrix_valued> g_in) {
    return make_gf_from_fourier<0, 1>(g_in);
  }
  auto make_gf_from_fourier(block_gf_view<prod<cyclat, dlr_imtime>, matrix_valued> g_in) {
    return map_block_gf([](auto &&g_bl) { return make_gf_from_fourier<0, 1>(make_const_view(g_bl)); }, g_in);
  }

} // namespace triqs::gfs
