// Generated by gf_factories.inst.py. Do not edit!
#pragma once

#include <triqs/gfs.hpp>
#include <triqs/gfs/functions/dlr.hpp>
#include <triqs/gfs/functions/imfreq.hpp>
#include <triqs/gfs/transform/fourier.hpp>
#include <triqs/mesh.hpp>

using namespace triqs::arrays;
using namespace triqs::gfs;
using namespace triqs::mesh;

namespace triqs::gfs {

  // make_hermitian: imfreq and imtime, target rank 0, 2, 4
  template gf<imfreq, scalar_valued> make_hermitian(gf_const_view<imfreq, scalar_valued> const &);
  template block_gf<imfreq, scalar_valued> make_hermitian(block_gf_const_view<imfreq, scalar_valued> const &);
  template block2_gf<imfreq, scalar_valued> make_hermitian(block2_gf_const_view<imfreq, scalar_valued> const &);
  template gf<imfreq, matrix_valued> make_hermitian(gf_const_view<imfreq, matrix_valued> const &);
  template block_gf<imfreq, matrix_valued> make_hermitian(block_gf_const_view<imfreq, matrix_valued> const &);
  template block2_gf<imfreq, matrix_valued> make_hermitian(block2_gf_const_view<imfreq, matrix_valued> const &);
  template gf<imfreq, tensor_valued<4>> make_hermitian(gf_const_view<imfreq, tensor_valued<4>> const &);
  template block_gf<imfreq, tensor_valued<4>> make_hermitian(block_gf_const_view<imfreq, tensor_valued<4>> const &);
  template block2_gf<imfreq, tensor_valued<4>> make_hermitian(block2_gf_const_view<imfreq, tensor_valued<4>> const &);
  template gf<imtime, scalar_valued> make_hermitian(gf_const_view<imtime, scalar_valued> const &);
  template block_gf<imtime, scalar_valued> make_hermitian(block_gf_const_view<imtime, scalar_valued> const &);
  template block2_gf<imtime, scalar_valued> make_hermitian(block2_gf_const_view<imtime, scalar_valued> const &);
  template gf<imtime, matrix_valued> make_hermitian(gf_const_view<imtime, matrix_valued> const &);
  template block_gf<imtime, matrix_valued> make_hermitian(block_gf_const_view<imtime, matrix_valued> const &);
  template block2_gf<imtime, matrix_valued> make_hermitian(block2_gf_const_view<imtime, matrix_valued> const &);
  template gf<imtime, tensor_valued<4>> make_hermitian(gf_const_view<imtime, tensor_valued<4>> const &);
  template block_gf<imtime, tensor_valued<4>> make_hermitian(block_gf_const_view<imtime, tensor_valued<4>> const &);
  template block2_gf<imtime, tensor_valued<4>> make_hermitian(block2_gf_const_view<imtime, tensor_valued<4>> const &);

  // make_real_in_tau: imfreq only, target rank 0, 2, 4
  template gf<imfreq, scalar_valued> make_real_in_tau(gf_const_view<imfreq, scalar_valued> const &);
  template block_gf<imfreq, scalar_valued> make_real_in_tau(block_gf_const_view<imfreq, scalar_valued> const &);
  template block2_gf<imfreq, scalar_valued> make_real_in_tau(block2_gf_const_view<imfreq, scalar_valued> const &);
  template gf<imfreq, matrix_valued> make_real_in_tau(gf_const_view<imfreq, matrix_valued> const &);
  template block_gf<imfreq, matrix_valued> make_real_in_tau(block_gf_const_view<imfreq, matrix_valued> const &);
  template block2_gf<imfreq, matrix_valued> make_real_in_tau(block2_gf_const_view<imfreq, matrix_valued> const &);
  template gf<imfreq, tensor_valued<4>> make_real_in_tau(gf_const_view<imfreq, tensor_valued<4>> const &);
  template block_gf<imfreq, tensor_valued<4>> make_real_in_tau(block_gf_const_view<imfreq, tensor_valued<4>> const &);
  template block2_gf<imfreq, tensor_valued<4>> make_real_in_tau(block2_gf_const_view<imfreq, tensor_valued<4>> const &);

  // make_gf_dlr: single mesh DLR conversions
  /**
   * @brief Transform a DLR imaginary-time or DLR Matsubara Green's function to its DLR-coefficient representation.
   *
   * @details Applies to every overload. The input lives on a single
   * DLR imaginary-time or DLR Matsubara frequency mesh, or on a
   * product mesh pairing a DLR axis with a lattice axis. Block and
   * block-of-block Green's function containers are handled
   * component-wise, and product meshes are handled axis-wise. All
   * target ranks (scalar, vector, matrix, rank-3, rank-4) are
   * supported.
   *
   * @param g The input Green's function.
   * @return The Green's function expressed in DLR coefficients.
   */
  auto make_gf_dlr(gf_const_view<dlr_imtime, scalar_valued> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(gf_const_view<dlr_imfreq, scalar_valued> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block_gf_const_view<dlr_imtime, scalar_valued> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block_gf_const_view<dlr_imfreq, scalar_valued> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block2_gf_const_view<dlr_imtime, scalar_valued> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block2_gf_const_view<dlr_imfreq, scalar_valued> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(gf_const_view<dlr_imtime, tensor_valued<1>> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(gf_const_view<dlr_imfreq, tensor_valued<1>> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block_gf_const_view<dlr_imtime, tensor_valued<1>> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block_gf_const_view<dlr_imfreq, tensor_valued<1>> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block2_gf_const_view<dlr_imtime, tensor_valued<1>> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block2_gf_const_view<dlr_imfreq, tensor_valued<1>> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(gf_const_view<dlr_imtime, matrix_valued> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(gf_const_view<dlr_imfreq, matrix_valued> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block_gf_const_view<dlr_imtime, matrix_valued> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block_gf_const_view<dlr_imfreq, matrix_valued> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block2_gf_const_view<dlr_imtime, matrix_valued> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block2_gf_const_view<dlr_imfreq, matrix_valued> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(gf_const_view<dlr_imtime, tensor_valued<3>> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(gf_const_view<dlr_imfreq, tensor_valued<3>> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block_gf_const_view<dlr_imtime, tensor_valued<3>> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block_gf_const_view<dlr_imfreq, tensor_valued<3>> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block2_gf_const_view<dlr_imtime, tensor_valued<3>> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block2_gf_const_view<dlr_imfreq, tensor_valued<3>> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(gf_const_view<dlr_imtime, tensor_valued<4>> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(gf_const_view<dlr_imfreq, tensor_valued<4>> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block_gf_const_view<dlr_imtime, tensor_valued<4>> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block_gf_const_view<dlr_imfreq, tensor_valued<4>> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block2_gf_const_view<dlr_imtime, tensor_valued<4>> const &g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block2_gf_const_view<dlr_imfreq, tensor_valued<4>> const &g) { return make_gf_dlr<0>(g); }

  // fit_gf_dlr: imtime -> dlr
  /**
   * @brief Fit an imaginary-time Green's function with a Discrete Lehmann Representation.
   *
   * @details Applies to every overload. The input lives on a single
   * imaginary-time mesh or on a product mesh pairing an
   * imaginary-time axis with a lattice axis. Block and block-of-block
   * Green's function containers are handled component-wise, and
   * product meshes are handled axis-wise. All target ranks (scalar,
   * vector, matrix, rank-3, rank-4) are supported. The DLR grid is
   * specified by the spectral cutoff ``w_max`` and the tolerance
   * ``eps``.
   *
   * @param g The imaginary-time Green's function to fit.
   * @param w_max Maximum real frequency captured by the DLR basis.
   * @param eps Target accuracy of the DLR representation.
   * @param symmetrize If true, the DLR grid is symmetric about zero frequency.
   * @return A Green's function on the DLR coefficient mesh.
   */
  auto fit_gf_dlr(gf_const_view<imtime, scalar_valued> const &g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(block_gf_const_view<imtime, scalar_valued> const &g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(block2_gf_const_view<imtime, scalar_valued> const &g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(gf_const_view<imtime, tensor_valued<1>> const &g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(block_gf_const_view<imtime, tensor_valued<1>> const &g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(block2_gf_const_view<imtime, tensor_valued<1>> const &g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(gf_const_view<imtime, matrix_valued> const &g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(block_gf_const_view<imtime, matrix_valued> const &g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(block2_gf_const_view<imtime, matrix_valued> const &g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(gf_const_view<imtime, tensor_valued<3>> const &g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(block_gf_const_view<imtime, tensor_valued<3>> const &g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(block2_gf_const_view<imtime, tensor_valued<3>> const &g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(gf_const_view<imtime, tensor_valued<4>> const &g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(block_gf_const_view<imtime, tensor_valued<4>> const &g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(block2_gf_const_view<imtime, tensor_valued<4>> const &g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }

  // make_gf_dlr: product mesh wrappers
  auto make_gf_dlr(gf_const_view<prod<dlr_imtime, brzone>, scalar_valued> g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(gf_const_view<prod<brzone, dlr_imtime>, scalar_valued> g) { return make_gf_dlr<1>(g); }
  auto make_gf_dlr(gf_const_view<prod<dlr_imfreq, brzone>, scalar_valued> g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(gf_const_view<prod<brzone, dlr_imfreq>, scalar_valued> g) { return make_gf_dlr<1>(g); }
  auto make_gf_dlr(gf_const_view<prod<dlr_imtime, cyclat>, scalar_valued> g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(gf_const_view<prod<cyclat, dlr_imtime>, scalar_valued> g) { return make_gf_dlr<1>(g); }
  auto make_gf_dlr(gf_const_view<prod<dlr_imfreq, cyclat>, scalar_valued> g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(gf_const_view<prod<cyclat, dlr_imfreq>, scalar_valued> g) { return make_gf_dlr<1>(g); }
  auto make_gf_dlr(block_gf_const_view<prod<dlr_imtime, brzone>, scalar_valued> g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block_gf_const_view<prod<brzone, dlr_imtime>, scalar_valued> g) { return make_gf_dlr<1>(g); }
  auto make_gf_dlr(block_gf_const_view<prod<dlr_imfreq, brzone>, scalar_valued> g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block_gf_const_view<prod<brzone, dlr_imfreq>, scalar_valued> g) { return make_gf_dlr<1>(g); }
  auto make_gf_dlr(block_gf_const_view<prod<dlr_imtime, cyclat>, scalar_valued> g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block_gf_const_view<prod<cyclat, dlr_imtime>, scalar_valued> g) { return make_gf_dlr<1>(g); }
  auto make_gf_dlr(block_gf_const_view<prod<dlr_imfreq, cyclat>, scalar_valued> g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block_gf_const_view<prod<cyclat, dlr_imfreq>, scalar_valued> g) { return make_gf_dlr<1>(g); }
  auto make_gf_dlr(gf_const_view<prod<dlr_imtime, brzone>, matrix_valued> g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(gf_const_view<prod<brzone, dlr_imtime>, matrix_valued> g) { return make_gf_dlr<1>(g); }
  auto make_gf_dlr(gf_const_view<prod<dlr_imfreq, brzone>, matrix_valued> g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(gf_const_view<prod<brzone, dlr_imfreq>, matrix_valued> g) { return make_gf_dlr<1>(g); }
  auto make_gf_dlr(gf_const_view<prod<dlr_imtime, cyclat>, matrix_valued> g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(gf_const_view<prod<cyclat, dlr_imtime>, matrix_valued> g) { return make_gf_dlr<1>(g); }
  auto make_gf_dlr(gf_const_view<prod<dlr_imfreq, cyclat>, matrix_valued> g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(gf_const_view<prod<cyclat, dlr_imfreq>, matrix_valued> g) { return make_gf_dlr<1>(g); }
  auto make_gf_dlr(block_gf_const_view<prod<dlr_imtime, brzone>, matrix_valued> g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block_gf_const_view<prod<brzone, dlr_imtime>, matrix_valued> g) { return make_gf_dlr<1>(g); }
  auto make_gf_dlr(block_gf_const_view<prod<dlr_imfreq, brzone>, matrix_valued> g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block_gf_const_view<prod<brzone, dlr_imfreq>, matrix_valued> g) { return make_gf_dlr<1>(g); }
  auto make_gf_dlr(block_gf_const_view<prod<dlr_imtime, cyclat>, matrix_valued> g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block_gf_const_view<prod<cyclat, dlr_imtime>, matrix_valued> g) { return make_gf_dlr<1>(g); }
  auto make_gf_dlr(block_gf_const_view<prod<dlr_imfreq, cyclat>, matrix_valued> g) { return make_gf_dlr<0>(g); }
  auto make_gf_dlr(block_gf_const_view<prod<cyclat, dlr_imfreq>, matrix_valued> g) { return make_gf_dlr<1>(g); }

  // fit_gf_dlr: product mesh wrappers
  auto fit_gf_dlr(gf_const_view<prod<imtime, brzone>, scalar_valued> g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(gf_const_view<prod<brzone, imtime>, scalar_valued> g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<1>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(gf_const_view<prod<imtime, cyclat>, scalar_valued> g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(gf_const_view<prod<cyclat, imtime>, scalar_valued> g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<1>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(block_gf_const_view<prod<imtime, brzone>, scalar_valued> g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(block_gf_const_view<prod<brzone, imtime>, scalar_valued> g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<1>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(block_gf_const_view<prod<imtime, cyclat>, scalar_valued> g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(block_gf_const_view<prod<cyclat, imtime>, scalar_valued> g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<1>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(gf_const_view<prod<imtime, brzone>, matrix_valued> g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(gf_const_view<prod<brzone, imtime>, matrix_valued> g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<1>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(gf_const_view<prod<imtime, cyclat>, matrix_valued> g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(gf_const_view<prod<cyclat, imtime>, matrix_valued> g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<1>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(block_gf_const_view<prod<imtime, brzone>, matrix_valued> g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(block_gf_const_view<prod<brzone, imtime>, matrix_valued> g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<1>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(block_gf_const_view<prod<imtime, cyclat>, matrix_valued> g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<0>(g, w_max, eps, symmetrize); }
  auto fit_gf_dlr(block_gf_const_view<prod<cyclat, imtime>, matrix_valued> g, double w_max, double eps, bool symmetrize = true) { return fit_gf_dlr<1>(g, w_max, eps, symmetrize); }

} // namespace triqs::gfs
