// Generated by gf_factories.inst.py. Do not edit!
#pragma once

#include <triqs/gfs.hpp>
#include <triqs/gfs/functions/dlr.hpp>
#include <triqs/gfs/functions/imfreq.hpp>
#include <triqs/gfs/transform/fourier.hpp>
#include <triqs/mesh.hpp>

using namespace triqs::arrays;
using namespace triqs::gfs;
using namespace triqs::mesh;

namespace triqs::gfs {

  // make_gf_dlr_imtime: from dlr and dlr_imfreq
  /**
   * @brief Build a DLR imaginary-time Green's function from a DLR-coefficient or DLR-Matsubara input.
   *
   * @details Applies to every overload. The input lives on a single
   * DLR coefficient mesh or DLR Matsubara frequency mesh, or on a
   * product mesh pairing a DLR axis with a lattice axis. Block and
   * block-of-block Green's function containers are handled
   * component-wise, and product meshes are handled axis-wise. All
   * target ranks (scalar, vector, matrix, rank-3, rank-4) are
   * supported. The output lives on the DLR imaginary-time mesh
   * associated with the input's DLR grid.
   *
   * @param g A Green's function on a DLR coefficient or DLR Matsubara frequency mesh.
   * @return The Green's function evaluated on the DLR imaginary-time mesh.
   */
  auto make_gf_dlr_imtime(gf_const_view<dlr, scalar_valued> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(gf_const_view<dlr_imfreq, scalar_valued> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block_gf_const_view<dlr, scalar_valued> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block_gf_const_view<dlr_imfreq, scalar_valued> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block2_gf_const_view<dlr, scalar_valued> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block2_gf_const_view<dlr_imfreq, scalar_valued> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(gf_const_view<dlr, tensor_valued<1>> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(gf_const_view<dlr_imfreq, tensor_valued<1>> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block_gf_const_view<dlr, tensor_valued<1>> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block_gf_const_view<dlr_imfreq, tensor_valued<1>> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block2_gf_const_view<dlr, tensor_valued<1>> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block2_gf_const_view<dlr_imfreq, tensor_valued<1>> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(gf_const_view<dlr, matrix_valued> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(gf_const_view<dlr_imfreq, matrix_valued> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block_gf_const_view<dlr, matrix_valued> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block_gf_const_view<dlr_imfreq, matrix_valued> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block2_gf_const_view<dlr, matrix_valued> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block2_gf_const_view<dlr_imfreq, matrix_valued> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(gf_const_view<dlr, tensor_valued<3>> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(gf_const_view<dlr_imfreq, tensor_valued<3>> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block_gf_const_view<dlr, tensor_valued<3>> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block_gf_const_view<dlr_imfreq, tensor_valued<3>> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block2_gf_const_view<dlr, tensor_valued<3>> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block2_gf_const_view<dlr_imfreq, tensor_valued<3>> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(gf_const_view<dlr, tensor_valued<4>> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(gf_const_view<dlr_imfreq, tensor_valued<4>> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block_gf_const_view<dlr, tensor_valued<4>> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block_gf_const_view<dlr_imfreq, tensor_valued<4>> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block2_gf_const_view<dlr, tensor_valued<4>> const &g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block2_gf_const_view<dlr_imfreq, tensor_valued<4>> const &g) { return make_gf_dlr_imtime<0>(g); }

  // make_gf_imtime: from dlr, dlr_imtime, dlr_imfreq
  /**
   * @brief Build a uniform imaginary-time Green's function from any DLR representation.
   *
   * @details Applies to every overload. The input lives on a single
   * DLR coefficient, DLR imaginary-time, or DLR Matsubara frequency
   * mesh, or on a product mesh pairing a DLR axis with a lattice
   * axis. Block and block-of-block Green's function containers are
   * handled component-wise, and product meshes are handled axis-wise.
   * All target ranks (scalar, vector, matrix, rank-3, rank-4) are
   * supported. Inputs on a DLR imaginary-time or DLR Matsubara
   * frequency mesh are first converted to DLR coefficients
   * internally.
   *
   * @param g A Green's function on a DLR coefficient, DLR imaginary-time, or DLR Matsubara frequency mesh.
   * @param n_tau Number of points of the output imaginary-time mesh.
   * @return The Green's function on a uniform imaginary-time mesh.
   */
  auto make_gf_imtime(gf_const_view<dlr, scalar_valued> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(gf_const_view<dlr_imtime, scalar_valued> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(gf_const_view<dlr_imfreq, scalar_valued> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block_gf_const_view<dlr, scalar_valued> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block_gf_const_view<dlr_imtime, scalar_valued> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block_gf_const_view<dlr_imfreq, scalar_valued> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block2_gf_const_view<dlr, scalar_valued> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block2_gf_const_view<dlr_imtime, scalar_valued> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block2_gf_const_view<dlr_imfreq, scalar_valued> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(gf_const_view<dlr, tensor_valued<1>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(gf_const_view<dlr_imtime, tensor_valued<1>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(gf_const_view<dlr_imfreq, tensor_valued<1>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block_gf_const_view<dlr, tensor_valued<1>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block_gf_const_view<dlr_imtime, tensor_valued<1>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block_gf_const_view<dlr_imfreq, tensor_valued<1>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block2_gf_const_view<dlr, tensor_valued<1>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block2_gf_const_view<dlr_imtime, tensor_valued<1>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block2_gf_const_view<dlr_imfreq, tensor_valued<1>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(gf_const_view<dlr, matrix_valued> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(gf_const_view<dlr_imtime, matrix_valued> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(gf_const_view<dlr_imfreq, matrix_valued> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block_gf_const_view<dlr, matrix_valued> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block_gf_const_view<dlr_imtime, matrix_valued> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block_gf_const_view<dlr_imfreq, matrix_valued> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block2_gf_const_view<dlr, matrix_valued> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block2_gf_const_view<dlr_imtime, matrix_valued> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block2_gf_const_view<dlr_imfreq, matrix_valued> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(gf_const_view<dlr, tensor_valued<3>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(gf_const_view<dlr_imtime, tensor_valued<3>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(gf_const_view<dlr_imfreq, tensor_valued<3>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block_gf_const_view<dlr, tensor_valued<3>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block_gf_const_view<dlr_imtime, tensor_valued<3>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block_gf_const_view<dlr_imfreq, tensor_valued<3>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block2_gf_const_view<dlr, tensor_valued<3>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block2_gf_const_view<dlr_imtime, tensor_valued<3>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block2_gf_const_view<dlr_imfreq, tensor_valued<3>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(gf_const_view<dlr, tensor_valued<4>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(gf_const_view<dlr_imtime, tensor_valued<4>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(gf_const_view<dlr_imfreq, tensor_valued<4>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block_gf_const_view<dlr, tensor_valued<4>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block_gf_const_view<dlr_imtime, tensor_valued<4>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block_gf_const_view<dlr_imfreq, tensor_valued<4>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block2_gf_const_view<dlr, tensor_valued<4>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block2_gf_const_view<dlr_imtime, tensor_valued<4>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block2_gf_const_view<dlr_imfreq, tensor_valued<4>> const &g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }

  // make_gf_dlr_imtime: product mesh wrappers
  auto make_gf_dlr_imtime(gf_const_view<prod<dlr, brzone>, scalar_valued> g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(gf_const_view<prod<brzone, dlr>, scalar_valued> g) { return make_gf_dlr_imtime<1>(g); }
  auto make_gf_dlr_imtime(gf_const_view<prod<dlr, cyclat>, scalar_valued> g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(gf_const_view<prod<cyclat, dlr>, scalar_valued> g) { return make_gf_dlr_imtime<1>(g); }
  auto make_gf_dlr_imtime(block_gf_const_view<prod<dlr, brzone>, scalar_valued> g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block_gf_const_view<prod<brzone, dlr>, scalar_valued> g) { return make_gf_dlr_imtime<1>(g); }
  auto make_gf_dlr_imtime(block_gf_const_view<prod<dlr, cyclat>, scalar_valued> g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block_gf_const_view<prod<cyclat, dlr>, scalar_valued> g) { return make_gf_dlr_imtime<1>(g); }
  auto make_gf_dlr_imtime(gf_const_view<prod<dlr, brzone>, matrix_valued> g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(gf_const_view<prod<brzone, dlr>, matrix_valued> g) { return make_gf_dlr_imtime<1>(g); }
  auto make_gf_dlr_imtime(gf_const_view<prod<dlr, cyclat>, matrix_valued> g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(gf_const_view<prod<cyclat, dlr>, matrix_valued> g) { return make_gf_dlr_imtime<1>(g); }
  auto make_gf_dlr_imtime(block_gf_const_view<prod<dlr, brzone>, matrix_valued> g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block_gf_const_view<prod<brzone, dlr>, matrix_valued> g) { return make_gf_dlr_imtime<1>(g); }
  auto make_gf_dlr_imtime(block_gf_const_view<prod<dlr, cyclat>, matrix_valued> g) { return make_gf_dlr_imtime<0>(g); }
  auto make_gf_dlr_imtime(block_gf_const_view<prod<cyclat, dlr>, matrix_valued> g) { return make_gf_dlr_imtime<1>(g); }

  // make_gf_imtime: product mesh wrappers
  auto make_gf_imtime(gf_const_view<prod<dlr, brzone>, scalar_valued> g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(gf_const_view<prod<brzone, dlr>, scalar_valued> g, long n_tau) { return make_gf_imtime<1>(g, n_tau); }
  auto make_gf_imtime(gf_const_view<prod<dlr, cyclat>, scalar_valued> g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(gf_const_view<prod<cyclat, dlr>, scalar_valued> g, long n_tau) { return make_gf_imtime<1>(g, n_tau); }
  auto make_gf_imtime(block_gf_const_view<prod<dlr, brzone>, scalar_valued> g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block_gf_const_view<prod<brzone, dlr>, scalar_valued> g, long n_tau) { return make_gf_imtime<1>(g, n_tau); }
  auto make_gf_imtime(block_gf_const_view<prod<dlr, cyclat>, scalar_valued> g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block_gf_const_view<prod<cyclat, dlr>, scalar_valued> g, long n_tau) { return make_gf_imtime<1>(g, n_tau); }
  auto make_gf_imtime(gf_const_view<prod<dlr, brzone>, matrix_valued> g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(gf_const_view<prod<brzone, dlr>, matrix_valued> g, long n_tau) { return make_gf_imtime<1>(g, n_tau); }
  auto make_gf_imtime(gf_const_view<prod<dlr, cyclat>, matrix_valued> g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(gf_const_view<prod<cyclat, dlr>, matrix_valued> g, long n_tau) { return make_gf_imtime<1>(g, n_tau); }
  auto make_gf_imtime(block_gf_const_view<prod<dlr, brzone>, matrix_valued> g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block_gf_const_view<prod<brzone, dlr>, matrix_valued> g, long n_tau) { return make_gf_imtime<1>(g, n_tau); }
  auto make_gf_imtime(block_gf_const_view<prod<dlr, cyclat>, matrix_valued> g, long n_tau) { return make_gf_imtime<0>(g, n_tau); }
  auto make_gf_imtime(block_gf_const_view<prod<cyclat, dlr>, matrix_valued> g, long n_tau) { return make_gf_imtime<1>(g, n_tau); }

} // namespace triqs::gfs
