"""
Generate gf_fnt_fourier.hpp with set_from_fourier wrapper overloads.

Matches the combinations from gf_fnt_desc.py:
  - 4 Matsubara/real mesh pairs x gf/block_gf/block2_gf x 5 targets
  - Real-valued input variant when input is a time mesh
  - Known-moments variant (gf only)
  - 2 lattice mesh pairs x gf/block_gf/block2_gf x 5 targets
"""

TARGETS = ["scalar_valued", "tensor_valued<1>", "matrix_valued", "tensor_valued<3>", "tensor_valued<4>"]
TARGET_RANK = {t: i for i, t in enumerate(TARGETS)}
TIME_MESHES = {"imtime", "retime"}
MESH_PAIRS = [("imfreq", "imtime"), ("imtime", "imfreq"), ("refreq", "retime"), ("retime", "refreq")]
LATTICE_PAIRS = [("cyclat", "brzone"), ("brzone", "cyclat")]
GF_TYPES = ["gf", "block_gf", "block2_gf"]


def real_valued(target):
    return target.replace("_valued", "_real_valued")


DOC = """\
  /**
   * @brief Fourier transform a Green's function in place from one mesh to its conjugate.
   *
   * @details Applies to every overload. The supported conjugate mesh
   * pairs are imaginary time and Matsubara frequencies, real time and
   * real frequency, and cyclic lattice and Brillouin zone. Block and
   * block-of-block Green's function containers are transformed block
   * by block. All target ranks (scalar, vector, matrix, rank-3,
   * rank-4) are supported. The output and input meshes are taken from
   * the two arguments; both containers must already have compatible
   * target shapes.
   *
   * For the imaginary-time and Matsubara and the real-time and
   * real-frequency pairs, an optional trailing array of high-frequency
   * moments (``known_moments``) may be passed; the known-moment tail
   * correction improves accuracy at high frequency.
   *
   * @param g_out The output Green's function on the conjugate mesh; modified in place.
   * @param g_in The input Green's function.
   */
"""

with open("gf_fnt_fourier.hpp", "w") as f:
    f.write("// Generated by gf_fnt_fourier.inst.py. Do not edit!\n")
    f.write("#pragma once\n\n")
    f.write('#include <triqs/gfs.hpp>\n')
    f.write('#include <triqs/mesh.hpp>\n\n')
    f.write("namespace triqs::gfs {\n")

    # Matsubara and real-time/frequency Fourier
    first_overload = True
    for target in TARGETS:
        f.write(f"\n  // {target}\n")
        for m_out, m_in in MESH_PAIRS:
            for gf in GF_TYPES:
                if first_overload:
                    f.write(DOC)
                    first_overload = False
                f.write(f"  void set_from_fourier({gf}_view<{m_out}, {target}> g_out, {gf}_const_view<{m_in}, {target}> g_in) {{ g_out = fourier(g_in); }}\n")

            # Real-valued input: only when input is a time mesh
            if m_in in TIME_MESHES:
                real_t = real_valued(target)
                for gf in GF_TYPES:
                    f.write(f"  void set_from_fourier({gf}_view<{m_out}, {target}> g_out, {gf}_const_view<{m_in}, {real_t}> g_in) {{ g_out = fourier(g_in); }}\n")

            # Known moments: gf only
            r = 1 + TARGET_RANK[target]
            f.write(f"  void set_from_fourier(gf_view<{m_out}, {target}> g_out, gf_const_view<{m_in}, {target}> g_in, array_const_view<dcomplex, {r}> known_moments) {{ g_out = fourier(g_in, known_moments); }}\n")

        # Lattice Fourier
        for m_out, m_in in LATTICE_PAIRS:
            for gf in GF_TYPES:
                f.write(f"  void set_from_fourier({gf}_view<{m_out}, {target}> g_out, {gf}_const_view<{m_in}, {target}> g_in) {{ g_out = fourier(g_in); }}\n")

    f.write("\n} // namespace triqs::gfs\n")
