def all_calls():
    validargs = {
        'imfreq' : ['long', 'matsubara_freq'],
        'imtime' : ['long', 'double'],
        'refreq' : ['long', 'double'],
        'retime' : ['long', 'double'],
        'legendre' : ['long', 'double'],
        'dlr'    : ['long', 'double', 'matsubara_freq'],
        'chebyshev' : ['long', 'double'],
        'brzone' : ['std::array<long,3>', 'std::array<double, 3>'],
        'cyclat' : ['std::array<long,3>', 'triqs::lattice::bravais_lattice::point_t']
        }
    target_and_return = [
        # rank, target, return_t
        [ 0, 'scalar_valued', 'dcomplex'],
        [ 1, 'tensor_valued<1>', 'array<dcomplex, 1>'],
        [ 2, 'matrix_valued', 'matrix<dcomplex>'],
        [ 3, 'tensor_valued<3>', 'array<dcomplex, 3>'],
        [ 4, 'tensor_valued<4>', 'array<dcomplex, 4>']
        ]

    meshes = ['imfreq', 'imtime', 'refreq', 'retime', 'legendre', 'dlr', 'chebyshev', 'brzone', 'cyclat']

    real_valued = lambda target: target.replace("_", "_real_")
    for rank, target, return_t in target_and_return:
        for M1 in meshes:
            xs = validargs[M1]
            nxs = len(xs)
            yield M1, [return_t]*nxs, rank, target, xs
            if M1 == 'imtime': yield M1, [return_t]*nxs, rank, real_valued(target), xs

            # Product Mesh Wrappings
            for M2 in meshes:
                if sum([M1 in ['brzone', 'cyclat'], M2 in ['brzone', 'cyclat']]) == 1:
                    ys = validargs[M2]
                    nys = len(ys)
                    arg_lst = [(x, y) for x in xs for y in ys] + [('all_t', y) for y in ys] + [(x, 'all_t') for x in xs]
                    ret_lst = [return_t]*nxs*nys + [f"gf<{M1}, {target}>"]*nys + [f"gf<{M2}, {target}>"]*nxs
                    yield 'prod<%s,%s>'%(M1,M2), ret_lst, rank, target, arg_lst
                    if 'imtime' in [M1, M2]:
                        ret_lst = [return_t]*nxs*nys + [f"gf<{M1}, {real_valued(target)}>"]*nys + [f"gf<{M2}, {real_valued(target)}>"]*nxs
                        yield 'prod<%s,%s>'%(M1,M2), ret_lst, rank, real_valued(target), arg_lst


# Fixme
C_py_transcript = {'imfreq' : 'ImFreq',
                   'refreq' : 'ReFreq',
                   'imtime' : 'ImTime',
                   'retime' : 'ReTime',
                   'legendre' : 'Legendre',
                   'dlr'    : 'DLR',
                   'chebyshev' : 'Chebyshev',
                   'dlr_imtime' : 'DLRImTime',
                   'dlr_imfreq' : 'DLRImFreq',
                   'brzone' : 'BrZone',
                   'cyclat' : 'CycLat',
                   'prod<brzone,imfreq>': 'BrZone_x_ImFreq',
                   'prod<brzone,imtime>': 'BrZone_x_ImTime',
                   'prod<brzone,refreq>': 'BrZone_x_ReFreq',
                   'prod<brzone,retime>': 'BrZone_x_ReTime',
                   'prod<brzone,legendre>'   : 'BrZone_x_Legendre',
                   'prod<brzone,dlr>'   : 'BrZone_x_DLR',
                   'prod<brzone,chebyshev>': 'BrZone_x_Chebyshev',
                   'prod<cyclat,imfreq>': 'CycLat_x_ImFreq',
                   'prod<cyclat,imtime>': 'CycLat_x_ImTime',
                   'prod<cyclat,refreq>': 'CycLat_x_ReFreq',
                   'prod<cyclat,retime>': 'CycLat_x_ReTime',
                   'prod<cyclat,legendre>'   : 'CycLat_x_Legendre',
                   'prod<cyclat,dlr>'   : 'CycLat_x_DLR',
                   'prod<cyclat,chebyshev>': 'CycLat_x_Chebyshev',
                   'prod<imfreq,brzone>': 'ImFreq_x_BrZone',
                   'prod<imtime,brzone>': 'ImTime_x_BrZone',
                   'prod<refreq,brzone>': 'ReFreq_x_BrZone',
                   'prod<retime,brzone>': 'ReTime_x_BrZone',
                   'prod<dlr,brzone>'   : 'DLR_x_BrZone',
                   'prod<legendre,brzone>'   : 'Legendre_x_BrZone',
                   'prod<chebyshev,brzone>'  : 'Chebyshev_x_BrZone',
                   'prod<imfreq,cyclat>': 'ImFreq_x_CycLat',
                   'prod<imtime,cyclat>': 'ImTime_x_CycLat',
                   'prod<refreq,cyclat>': 'ReFreq_x_CycLat',
                   'prod<retime,cyclat>': 'ReTime_x_CycLat',
                   'prod<dlr,cyclat>'   : 'DLR_x_CycLat',
                   'prod<legendre,cyclat>'   : 'Legendre_x_CycLat',
                   'prod<chebyshev,cyclat>'  : 'Chebyshev_x_CycLat',
                   }


with open("wrapped_aux.inst.cpp", "w") as f:
    f.write("// This file is automatically generated by wrapped_aux_desc.py. Do not edit !\n\n ")
    f.write("namespace c2py_module {\n\n")
    for mesh, return_t, R, target_t, point_t in all_calls():
        c_type = f"gf_proxy<gf_view<{mesh},{target_t}>>"
        c_py_trans = C_py_transcript[mesh]
        RE = "_R" if "_real_" in target_t else ""
        f.write(f"using CallProxy{c_py_trans}_{R}{RE} = triqs::gfs::{c_type};\n")

    f.write("}\n")

    for mesh, return_t, R, target_t, point_t in all_calls():
        full_c_type = f"triqs::gfs::gf_proxy<gf_view<{mesh},{target_t}>>"
        for P, Ret in zip(point_t, return_t):
            if not isinstance(P, tuple):
                f.write(f"extern template {Ret} {full_c_type}::call<{Ret}>({P} const&);\n")
            else:
                args = ', '.join(f'{t} const&' for t in P)
                f.write(f"extern template {Ret} {full_c_type}::call<{Ret}>({args});\n")
