package_name = "triqs.experimental.utility"
documentation = "Experimental utility tools (root finder, adaptive integration)"
namespaces = "triqs::experimental::utility"
match_names = "triqs::experimental::utility::(root_finder|find_bounds|dichotomy|bisection)"
wrap_no_arg_methods_as_properties = true
