FROM docker.io/intel/oneapi-hpckit:2025.3.1-0-devel-ubuntu24.04
ENV LLVM=20

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      clang-${LLVM} \
      g++ \
      git \
      vim \
      lldb-${LLVM} \
      hdf5-tools \
      libboost-dev \
      libclang-${LLVM}-dev \
      libc++-${LLVM}-dev \
      libc++abi-${LLVM}-dev \
      libzstd-dev \
      libfftw3-dev \
      libgmp-dev \
      libhdf5-dev \
      python3-clang-${LLVM} \
      python3-dev \
      python3-mako \
      python3-matplotlib \
      python3-numpy \
      python3-pip \
      python3-scipy \
      python3-venv

ENV PYTHON_VERSION=3.12 \
    CC=icx CXX=icpx CXXFLAGS="-stdlib=libc++" \
    CPLUS_INCLUDE_PATH=/usr/lib/llvm-${LLVM}/include/c++/v1 \
    VIRTUAL_ENV=/home/venv \
    PATH=/home/venv/bin:$PATH

RUN python3 -m venv --system-site-packages $VIRTUAL_ENV && pip install mpi4py cmake
