// Copyright (c) 2014-2018 Commissariat à l'énergie atomique et aux énergies alternatives (CEA)
// Copyright (c) 2014-2018 Centre national de la recherche scientifique (CNRS)
// Copyright (c) 2018-2023 Simons Foundation
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You may obtain a copy of the License at
//     https://www.gnu.org/licenses/gpl-3.0.txt
//
// Authors: Michel Ferrero, Olivier Parcollet, Nils Wentzell

/**
 * @file
 * @brief Provides a Bravais lattice class.
 */

#pragma once

#include "../arrays.hpp"

#include <fmt/ranges.h>
#include <h5/h5.hpp>
#include <nda/nda.hpp>

#include <array>
#include <iostream>
#include <optional>
#include <string>
#include <vector>

namespace triqs::lattice {

  /**
   * @addtogroup triqs-lattice
   * @{
   */

  /// Real space vector type.
  using r_t = nda::vector<double>;

  /// Matrix type for transformations involving real and reciprocal space vectors.
  using matrix_t = nda::matrix<double>;

  /**
   * @brief A Bravais lattice class.
   *
   * @details A Bravais lattice in \f$ d \f$ dimensions is defined by
   * - a set of linear independent d-dimensional basis vectors \f$ \{ \mathbf{a}_1, \dots, \mathbf{a}_d \} \f$ and
   * - the positions, \f$ \{ \mathbf{r}_1, \dots, \mathbf{r}_m \} \f$, of atomic orbitals within each unit cell.
   *
   * Optionally, the atomic orbitals can be named.
   *
   * The infinite lattice points \f$ \mathbf{R}^{\mathbf{n}} \f$ (see bravais_lattice::point_t) are generated by
   * \f[
   *   \mathbf{R}^{\mathbf{n}} = \sum_{i=1}^{d} \mathbf{a}_i n_i = \mathbf{A} \mathbf{n} \; ,
   * \f]
   * where \f$ \mathbf{n} = (n_1, \dots, n_d) \in \mathbb{Z}^d \f$ is an index vector (or more formally the vector \f$
   * \mathbf{R}^{\mathbf{n}} \f$ in the lattice basis) and \f$ \mathbf{A} = \big( \mathbf{a}_1 \cdots \mathbf{a}_d \big) 
   * \f$ is the matrix with the basis vectors as its columns.
   *
   * @note Although the supported dimensions are 1, 2 and 3, the index vectors are always 3-dimensional, i.e. \f$
   * \mathbf{n} = (n_1, n_2, n_3) \f$. Indices \f$ n_j \f$ with \f$ j > d \f$ are simply ignored.
   */
  class bravais_lattice {
    public:
    /// Index type for lattice points on the Bravais lattice.
    using index_t = std::array<long, 3>;

    /**
     * @brief Construct a Bravais Lattice with given basis vectors and positions of atomic orbitals with optional names.
     *
     * @details The matrix \f$ \mathbf{A}^T \f$ containing the basis vectors as its rows is required to be square. The 
     * number of dimensions of the Bravais lattices is determined by the size of the matrix.
     *
     * @param A_T Matrix with the basis vectors \f$ \{ \mathbf{a}_1, \dots, \mathbf{a}_d \} \f$ as its rows.
     * @param orb_pos Atomic orbital positions \f$ \{ \mathbf{r}_1, \dots, \mathbf{r}_m \} \f$ in the unit cell.
     * @param orb_name Optional names for the atomic orbitals.
     */
    bravais_lattice(matrix_t const &A_T, std::vector<r_t> orb_pos = std::vector<r_t>{{0, 0, 0}}, std::vector<std::string> orb_name = {});

    /**
     * @brief Construct a simple cubic lattice with lattice constant \f$ a = 1 \f$.
     * @details The only atomic orbital is placed at the origin with no name.
     */
    bravais_lattice() : bravais_lattice(nda::eye<double>(3)) {}

    /// Check if a given vector \f$ \mathbf{r} \f$ is part of the domain.
    [[nodiscard]] bool contains(r_t const &) const { return true; }

    /// Get the number of dimensions of the Bravais lattice.
    [[nodiscard]] int ndim() const { return ndim_; }

    /// Get the matrix \f$ \mathbf{A}^T \f$ containing basis vectors as its rows.
    [[nodiscard]] matrix_t const &units() const { return units_; }

    /// Get the number of atomic orbitals in the unit cell.
    [[nodiscard]] long n_orbitals() const { return static_cast<long>(atom_orb_pos.size()); }

    /// Get a `std::vector<r_t>` containing the atomic orbital positions \f$ \{\mathbf{r}_1, \dots, \mathbf{r}_m\} \f$.
    [[nodiscard]] auto const &orbital_positions() const { return atom_orb_pos; }

    /// Get a `std::vector<std::string>` containing the orbital names.
    [[nodiscard]] auto const &orbital_names() const { return atom_orb_name; }

    /**
     * @brief Lattice point of a Bravais lattice.
     *
     * @details A lattice point is defined by an index vector, \f$ \mathbf{n} = (n_1, \dots, n_d) \f$, and the Bravais
     * lattice it belongs to.
     *
     * The corresponding lattice vector, \f$ \mathbf{R}^{\mathbf{n}} = (R^{\mathbf{n}}_1, \dots,  R^{\mathbf{n}}_d) \f$, 
     * can be obtained with
     * \f[
     *   \mathbf{R}^{\mathbf{n}} = \sum_{i=1}^{d} \mathbf{a}_i n_i \; ,
     * \f]
     * where \f$ \{ \mathbf{a}_1, \dots, \mathbf{a}_d \} \f$ are the basis vectors of the underlying Bravais lattice.
     *
     * @note Although the supported dimensions are 1, 2 and 3, the index vectors are always 3-dimensional, i.e. \f$
     * \mathbf{n} = (n_1, n_2, n_3) \f$. Indices \f$ n_j \f$ with \f$ j > d \f$ are simply ignored.
     */
    struct point_t {
      private:
      index_t _index                   = {0, 0, 0};
      bravais_lattice const *_bl_ptr   = nullptr;
      mutable std::optional<r_t> _rval = {};

      public:
      /// Default constructor leaves the lattice point uninitialized, i.e. belonging to no Bravais lattice.
      point_t() = default;

      /**
       * @brief Construct a lattice point with a given index vector on the given Bravais lattice.
       *
       * @param n Index vector \f$ \mathbf{n} \f$.
       * @param bl_ptr Pointer to the Bravais lattice.
       */
      point_t(index_t const &n, bravais_lattice const *bl_ptr) : _index(n), _bl_ptr(bl_ptr) {}

      /// Get the index vector \f$ \mathbf{n} \f$ of the lattice point.
      [[nodiscard]] auto index() const { return _index; }

      /// Get the underlying Bravais lattice.
      [[nodiscard]] auto const &lattice() const { return *_bl_ptr; }

      /**
       * @brief Conversion to the corresponding lattice vector \f$ \mathbf{R}^{\mathbf{n}} = \sum_{i=1}^{d} \mathbf{a}_i
       * n_i \f$.
       */
      explicit operator r_t() const {
        if (_rval)
          return *_rval;
        else
          return *(_rval = _bl_ptr->lattice_to_real_coordinates(_index));
      }

      /**
       * @brief Get the coordinate \f$ R^{\mathbf{n}}_i \f$ of the corresponding lattice vector \f$ 
       * \mathbf{R}^{\mathbf{n}} \f$.
       *
       * @deprecated Use operator[]() instead.
       */
      [[deprecated("() is deprecated for a cyclat::mesh_point_t. Use [] instead")]] double operator()(int d) const { return r_t(*this)[d]; }

      /**
       * @brief Get the coordinate \f$ R^{\mathbf{n}}_i \f$ of the corresponding lattice vector \f$
       * \mathbf{R}^{\mathbf{n}} \f$.
       *
       * @param i Dimension index \f$ i \f$.
       * @return Lattice vector coordinate \f$ R^{\mathbf{n}}_i \f$.
       */
      double operator[](int i) const { return r_t(*this)[i]; }

      /**
       * @brief Add two lattice points \f$ \mathbf{R}^{\mathbf{n}} \f$ and \f$ \mathbf{R}^{\mathbf{m}} \f$.
       *
       * @param pt Lattice point \f$ \mathbf{R}^{\mathbf{m}} \f$ (has to belong to the same Bravais lattice).
       * @return Lattice point corresponding to the lattice vector \f$ \mathbf{R}^{\mathbf{n}} +
       * \mathbf{R}^{\mathbf{m}} \f$.
       */
      [[nodiscard]] point_t operator+(point_t const &pt) const {
        EXPECTS(*_bl_ptr == *(pt._bl_ptr));
        return {_index + pt._index, _bl_ptr};
      }

      /**
       * @brief Subtract two lattice points \f$ \mathbf{R}^{\mathbf{n}} \f$ and \f$ \mathbf{R}^{\mathbf{m}} \f$.
       *
       * @param pt Lattice point \f$ \mathbf{R}^{\mathbf{m}} \f$ (has to belong to the same Bravais lattice).
       * @return Lattice point corresponding to the lattice vector \f$ \mathbf{R}^{\mathbf{n}} -
       * \mathbf{R}^{\mathbf{m}} \f$.
       */
      [[nodiscard]] point_t operator-(point_t const &pt) const {
        EXPECTS(*_bl_ptr == *(pt._bl_ptr));
        return {_index - pt._index, _bl_ptr};
      }

      /**
       * @brief Invert the lattice point \f$ \mathbf{R}^{\mathbf{n}} \f$.
       * @return Lattice point corresponding to the lattice vector \f$ -\mathbf{R}^{\mathbf{n}} \f$.
       */
      [[nodiscard]] point_t operator-() const { return {-_index, _bl_ptr}; }

      /**
       * @brief Write a lattice point to a `std::ostream`.
       *
       * @param sout `std::ostream` object.
       * @param pt Lattice point to be written.
       * @return Reference to `std::ostream` object.
       */
      friend std::ostream &operator<<(std::ostream &sout, point_t const &pt) { return sout << static_cast<r_t>(pt); }
    };

    /**
     * @brief Transform a vector \f$ \mathbf{v} \f$ from the lattice basis \f$ \{ \mathbf{a}_1, \dots, \mathbf{a}_d \}
     * \f$ to the standard basis \f$ \{ \mathbf{e}_1, \dots, \mathbf{e}_d \} \f$.
     *
     * @details The transformed vector is given by
     * \f[
     *   \tilde{\mathbf{v}} = \sum_{i=1}^{d} \mathbf{a}_i v_i = A \mathbf{v} \; ,
     * \f]
     * where \f$ A \f$ is the matrix with the lattice basis vectors as its columns.
     *
     * @param v Vector \f$ \mathbf{v} \f$ to be transformed.
     * @return Vector \f$ \tilde{\mathbf{v}} \f$ in the standard basis.
     */
    template <typename R> [[nodiscard]] r_t lattice_to_real_coordinates(R const &v) const {
      return nda::transpose(units_)(nda::range::all, nda::range(ndim())) * nda::basic_array_view{v}(nda::range(ndim()));
    }

    /**
     * @brief Transform a vector \f$ \tilde{\mathbf{v}} \f$ from the standard basis \f$ \{ \mathbf{e}_1, \dots,
     * \mathbf{e}_d \} \f$ to the lattice basis \f$ \{ \mathbf{a}_1, \dots, \mathbf{a}_d \} \f$.
     *
     * @details This is the inverse transformation of lattice_to_real_coordinates(). The transformed vector is therefore
     * given by \f$ \mathbf{v} = A^{-1} \tilde{\mathbf{v}} \f$.
     *
     * @param v_tilde Vector \f$ \tilde{\mathbf{v}} \f$ in the standard basis.
     * @return Vector \f$ \mathbf{v} \f$ in the lattice basis.
     */
    template <typename R> [[nodiscard]] r_t real_to_lattice_coordinates(R const &v_tilde) const {
      return nda::transpose(units_inv_)(nda::range::all, nda::range(ndim())) * nda::basic_array_view{v_tilde}(nda::range(ndim()));
    }

    /**
     * @brief Convert an index vector to a lattice point.
     *
     * @param n Index vector \f$ \mathbf{n} \f$.
     * @return bravais_lattice::point_t corresponding to the given index array.
     */
    [[nodiscard]] point_t to_point(index_t const &n) const { return {n, this}; }

    /**
     * @brief Equal-to comparison operator.
     * @return True, if the number of dimensions, unit cell basis vectors and the atomic orbital positions are equal.
     */
    bool operator==(bravais_lattice const &bl) const { return units_ == bl.units() && ndim_ == bl.ndim() && n_orbitals() == bl.n_orbitals(); }

    /**
     * @brief Not-equal-to comparison operator.
     * @return True, if the number of dimensions, unit cell basis vectors or the atomic orbital positions are not equal.
     */
    bool operator!=(bravais_lattice const &bl) const { return !(operator==(bl)); }

    /**
     * @brief Write a triqs::lattice::bravais_lattice to a `std::ostream`.
     *
     * @param sout `std::ostream` object.
     * @param bl Bravais lattice to be written.
     * @return Reference to `std::ostream` object.
     */
    friend std::ostream &operator<<(std::ostream &sout, bravais_lattice const &bl) {
      return sout << "Bravais Lattice with dimension " << bl.ndim() << ", units " << bl.units() << ", n_orbitals " << bl.n_orbitals();
    }

    /**
     * @brief Serialize the Bravais lattice to a generic archive.
     * @param ar Archive to serialize to.
     */
    void serialize(auto &ar) const { ar & ndim_ & units_ & atom_orb_pos & atom_orb_name; }

    /**
     * @brief Deserialize the Bravais lattice from a generic archive.
     * @param ar Archive to deserialize from.
     */
    void deserialize(auto &ar) { ar & ndim_ & units_ & atom_orb_pos & atom_orb_name; }

    /// Get the HDF5 format tag.
    [[nodiscard]] static std::string hdf5_format() { return "bravais_lattice"; }

    /**
     * @brief Write a triqs::lattice::bravais_lattice to HDF5.
     *
     * @param g `h5::group` to be written to.
     * @param name Name of the subgroup.
     * @param bl Bravais lattice object to be written.
     */
    friend void h5_write(h5::group g, std::string const &name, bravais_lattice const &bl);

    /**
     * @brief Read a triqs::lattice::bravais_lattice from HDF5.
     *
     * @param g `h5::group` to be read from.
     * @param name Name of the subgroup.
     * @param bl Bravais lattice object to be read into.
     */
    friend void h5_read(h5::group g, std::string const &name, bravais_lattice &bl);

    private:
    matrix_t units_     = matrix_t::zeros(3, 3);
    matrix_t units_inv_ = matrix_t::zeros(3, 3);
    std::vector<r_t> atom_orb_pos;
    std::vector<std::string> atom_orb_name;
    int ndim_;
  };

  /** @} */

} // namespace triqs::lattice
