package_name = "triqs.experimental.lattice"
documentation = "Experimental lattice tools (tight binding, BZ integration, gloc, Wannier loaders)"
namespaces = "triqs::experimental::lattice"
# done by file to avoid wrapping fourier_polynomial
match_files = "bz_integrators.hpp|tb_hk.hpp|gloc.hpp|superlattice.hpp|wannier_loader.hpp|root_finder.hpp"
wrap_no_arg_methods_as_properties = true