// Copyright (c) 2015-2018 Commissariat à l'énergie atomique et aux énergies alternatives (CEA)
// Copyright (c) 2015-2018 Centre national de la recherche scientifique (CNRS)
// Copyright (c) 2018-2022 Simons Foundation
// Copyright (c) 2016 Igor Krivenko
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You may obtain a copy of the License at
//     https://www.gnu.org/licenses/gpl-3.0.txt
//
// Authors: Michel Ferrero, Igor Krivenko, Olivier Parcollet, Nils Wentzell

/**
 * @file
 * @brief Provides a class to represent Hilbert (Fock) spaces.
 */

#pragma once

#include "./fundamental_operator_set.hpp"
#include "../utility/exceptions.hpp"

#include <boost/container/flat_map.hpp>
#include <h5/h5.hpp>

#include <cstdint>
#include <set>
#include <string>
#include <vector>

namespace triqs::hilbert_space {

  /**
   * @addtogroup triqs-ops
   * @{
   */

  /**
   * @brief Integer type representing a fermionic fock state \f$ \lvert f \rangle = \lvert n_{\alpha_0}, n_{\alpha_1},
   * \dots, n_{\alpha_{N-1}} \rangle \f$.
   *
   * @details The least significant bit encodes the occupation of \f$ \lvert \alpha_0 \rangle \f$ and the most
   * significant bit of \f$ \lvert \alpha_{N-1} \rangle \f$.
   */
  using fock_state_t = uint64_t;

  /**
   * @brief Fermionic Hilbert (Fock) space generated by a fundamental operator set.
   *
   * @details The Hilbert (Fock) space \f$ \mathcal{F} \f$ is fully defined by its underlying fundamental operator set
   * \f$ A = \{ \alpha_i \}_{i=0}^{N-1} \f$ (see triqs::hilbert_space::fundamental_operator_set). Its dimension is \f$
   * \dim(\mathcal{F}) = 2^N \f$.
   *
   * As explained in @ref triqs-ops, we can map each occupation number basis state \f$ \lvert n_{\alpha_0}, 
   * n_{\alpha_1}, \dots, n_{\alpha_{N-1}} \rangle = \lvert f \rangle \in \mathcal{F} \f$ to an integer \f$ f \in \{ 0,
   * \dots, 2^N - 1 \} \f$ and back. This allows us to write the complete set of basis states of \f$ \mathcal{F} \f$ as
   * \f$ B_{\mathcal{F}} = \{ \lvert f \rangle \}_{f=0}^{2^N - 1} \f$. Furthermore, it imposes a natural order on \f$
   * B_{\mathcal{F}} \f$ such that \f$ \lvert f \rangle < \lvert f' \rangle \f$ if \f$ f < f' \f$.
   * 
   * @note This class is a minimal implementation of a Hilbert space. It only stores its dimension and relies completely
   * on the encoding of occupation number basis states as integers.
   */
  class hilbert_space {
    public:
    /// Default constructor constructs an empty Hilbert (Fock) space of dimension \f$ 0 \f$.
    hilbert_space() : dim_(0) {}

    /**
     * @brief Construct a Hilbert (Fock) space from a given triqs::hilbert_space::fundamental_operator_set object.
     *
     * @details If the size of the fundamental operator set is \f$ N \f$, then the dimension of the constructed Hilbert
     * (Fock) space is \f$ \dim(\mathcal{F}) = 2^N \f$.
     *
     * @param fops Fundamental operator set that generates the Hilbert (Fock) space.
     */
    hilbert_space(fundamental_operator_set const &fops) : dim_(static_cast<int>(1ull << fops.size())) {}

    /// Get the dimension \f$ \dim(\mathcal{F}) \f$ of the Hilbert (Fock) space \f$ \mathcal{F} \f$.
    [[nodiscard]] auto size() const { return dim_; }

    /// Equal-to operator compares the dimensions of the two Hilbert (Fock) spaces.
    bool operator==(hilbert_space const &hs) const { return dim_ == hs.dim_; }

    /**
     * @brief Check if a given Fock state belongs to the Hilbert (Fock) space.
     *
     * @param f Fock state \f$ \lvert f \rangle \f$.
     * @return True if \f$ f < 2^N = \dim{\mathcal{F}} \f$, false otherwise.
     */
    [[nodiscard]] bool has_state(fock_state_t f) const { return f < dim_; }

    /**
     * @brief Get the integer \f$ f \f$ corresponding to a given Fock state \f$ \lvert f \rangle \f$.
     *
     * @details It throws an exception if the given Fock state is not in the Hilbert (Fock) space, i.e. if \f$ f \geq 
     * 2^N = \dim{\mathcal{F}} \f$.
     *
     * @param f Fock state \f$ \lvert f \rangle \f$.
     * @return Integer \f$ f \f$.
     */
    [[nodiscard]] auto get_state_index(fock_state_t f) const {
      if (f >= dim_) TRIQS_RUNTIME_ERROR << "Error in hilbert_space::get_state_index: Fock state is not in H: f = " << f;
      return static_cast<int>(f);
    }

    /**
     * @brief Get the Fock state \f$ \lvert f \rangle \f$ corresponding to a given integer \f$ f \f$.
     *
     * @details It throws an exception if \f$ f \geq 2^N = \dim{\mathcal{F}} \f$.
     *
     * @param f Integer \f$ f \f$ representing the Fock state \f$ \lvert f \rangle \f$.
     * @return Fock state \f$ \lvert f \rangle \f$.
     */
    [[nodiscard]] fock_state_t get_fock_state(int f) const {
      if (f >= dim_) TRIQS_RUNTIME_ERROR << "Error in hilbert_space::get_fock_state: Index is >= dim(H): " << f;
      return f;
    }

    /**
     * @brief Get the Fock state \f$ \lvert f \rangle = \prod_{j=1}^k c^\dagger_{\alpha_{i_j}} \lvert 0 \rangle \f$.
     *
     * @param fops triqs::hilbert_space::fundamental_operator_set object that defines the Hilbert (Fock) space \f$ 
     * \mathcal{F} \f$.
     * @param alphas Set of indices \f$ \{ \alpha_{i_1}, \dots, \alpha_{i_k} \} \f$ specifying the creation operators.
     * @return Fock state \f$ \lvert f \rangle \f$.
     */
    [[nodiscard]] fock_state_t get_fock_state(fundamental_operator_set const &fops,
                                              std::set<fundamental_operator_set::indices_t> const &alphas) const {
      fock_state_t f = 0;
      for (auto const &alpha : alphas) f += 1 << fops[alpha];
      return f;
    }

    /// Get the HDF5 format tag.
    [[nodiscard]] static std::string hdf5_format() { return "hilbert_space"; }

    /**
     * @brief Write a triqs::hilbert_space::hilbert_space to HDF5.
     *
     * @param g `h5::group` to be written to.
     * @param name Name of the subgroup.
     * @param hs Hilbert (Fock) space to be written.
     */
    friend void h5_write(h5::group g, std::string const &name, hilbert_space const &hs) {
      auto gr = g.create_group(name);
      h5::write(gr, "dim", hs.dim_);
    }

    /**
     * @brief Read a triqs::hilbert_space::hilbert_space from HDF5.
     *
     * @param g `h5::group` to be read from.
     * @param name Name of the subgroup.
     * @param hs Hilbert (Fock) space to be read into.
     */
    friend void h5_read(h5::group g, std::string const &name, hilbert_space &hs) {
      auto gr = g.open_group(name);
      h5::read(gr, "dim", hs.dim_);
    }

    private:
    int dim_;
  };

  /**
   * @brief Subspace of a fermionic Hilbert (Fock) space.
   *
   * @details A subspace \f$ \mathcal{F}^{(m)} \subseteq \mathcal{F} \f$ of a triqs::hilbert_space::hilbert_space \f$
   * \mathcal{F} \f$ is defined by an ordered subset of occupation number basis states \f$ B_{\mathcal{F}^{(m)} } = \{ 
   * \lvert f_0 \rangle, \dots, \lvert f_{M-1} \rangle \} \subseteq B_{\mathcal{F}} \f$ such that \f$ 
   * \dim(\mathcal{F}^{(m)}) = M \leq \dim(\mathcal{F}) \f$.
   * 
   * The order of the Fock states on \f$ B_{\mathcal{F}^{(m)}} \f$ is defined as \f$ \lvert f_i \rangle < \lvert f_j 
   * \rangle \f$ if \f$ i < j \f$. This is not necessarily the same order as on \f$ B_{\mathcal{F}} \f$, where \f$
   * \lvert f_i \rangle < \lvert f_j \rangle \f$ if \f$ f_i < f_j \f$.
   *
   * For fast lookup, we store
   * - \f$ B_{\mathcal{F}^{(m)}} \f$, the ordered set of basis states in the subspace, as well as
   * - a map from the Fock state \f$ \lvert f_i \rangle \f$ to the corresponding index \f$ i \in \{ 0, 1, \dots, M-1
   * \} \f$ within the ordered set of the subspace.
   *
   * The subspace index \f$ m \f$ is used to distinguish between different subspaces of the same Hilbert (Fock) space.
   */
  class sub_hilbert_space {
    public:
    /**
     * @brief Construct an empty subspace with a given index \f$ m \f$.
     * @param m Subspace index \f$ m \f$.
     */
    sub_hilbert_space(int m = -1) : m_(m) {}

#ifdef TRIQS_WORKAROUND_INTEL_COMPILER_BUGS
    // Workaround needed for icc, checked with 17.0.1 20161005)
    sub_hilbert_space(sub_hilbert_space const &) = default;
    sub_hilbert_space(sub_hilbert_space &&)      = default;
    sub_hilbert_space &operator=(sub_hilbert_space const &x) {
      index         = x.index;
      fock_states   = x.fock_states;
      fock_to_index = x.fock_to_index;
      return *this;
    }
    sub_hilbert_space &operator=(sub_hilbert_space &&) = default;
#endif

    /**
     * @brief Add a Fock state \f$ \lvert f \rangle \f$ to the subspace and increase its dimension by one.
     *
     * @details Given that the current dimension of the subspace is \f$ M \f$, the added state will be assigned the
     * index \f$ M \f$ within the ordered set of Fock states of the subspace and the dimension of the subspace will be
     * increased to \f$ M + 1 \f$.
     *
     * @note We do not check if the given state is already present in the subspace.
     *
     * @param f Fock state \f$ \lvert f \rangle \f$ to be added.
     */
    void add_fock_state(fock_state_t f) {
      int const M = static_cast<int>(fock_states_.size());
      fock_states_.push_back(f);
      fock_to_index_.insert(std::make_pair(f, M));
    }

    /// Get the dimension \f$ M = \dim(\mathcal{F}^{(m)}) \f$ of the subspace.
    [[nodiscard]] auto size() const { return static_cast<int>(fock_states_.size()); }

    /// Equal-to operator compares the subspace index \f$ m \f$ and the ordered set \f$ B_{\mathcal{F}^{(m)}} \f$.
    bool operator==(sub_hilbert_space const &hs) const { return m_ == hs.m_ && fock_states_ == hs.fock_states_; }

    /**
     * @brief Get the index \f$ i \f$ of a given Fock state \f$ \lvert f_i \rangle \f$ within this subspace.
     *
     * @note We do not check if the given state is present in the subspace.
     *
     * @param f Fock state \f$ \lvert f_i \rangle \f$.
     * @return Integer \f$ i \f$.
     */
    [[nodiscard]] auto get_state_index(fock_state_t f) const { return fock_to_index_.find(f)->second; }

    /**
     * @brief Check if a given Fock state \f$ \lvert f \rangle \f$ belongs to this subspace.
     *
     * @param f Fock state \f$ \lvert f \rangle \f$.
     * @return True if \f$ f = f_i \f$ for some \f$ \lvert f_i \rangle \in \mathcal{F}^{(m)} \f$, false otherwise.
     */
    [[nodiscard]] bool has_state(fock_state_t f) const { return fock_to_index_.count(f) == 1; }

    /**
     * @brief Get the Fock state \f$ \lvert f_i \rangle \in \mathcal{F}^{(m)} \f$ for a given index \f$ i \f$.
     *
     * @param i Integer \f$ i \f$ representing the Fock state \f$ \lvert f_i \rangle \f$.
     * @return Fock state \f$ \lvert f_i \rangle \f$.
     */
    [[nodiscard]] auto get_fock_state(int i) const { return fock_states_[i]; }

    /// Get \f$ B_{\mathcal{F}^{(m)}} \f$, the ordered set of all Fock states in the subspace.
    [[nodiscard]] auto const &get_all_fock_states() const { return fock_states_; }

    /// Get the subspace index \f$ m \f$.
    [[nodiscard]] auto get_index() const { return m_; };

    /**
     * @brief Set the subspace index \f$ m \f$ of this subspace \f$ \mathcal{F}^{(m)} \f$.
     * @param m New index \f$ m \f$.
     */
    void set_index(int m) { m_ = m; }

    /// Get the HDF5 format tag.
    [[nodiscard]] static std::string hdf5_format() { return "sub_hilbert_space"; }

    /**
     * @brief Write a triqs::hilbert_space::sub_hilbert_space to HDF5.
     *
     * @param g `h5::group` to be written to.
     * @param name Name of the subgroup.
     * @param hs Subspace to be written.
     */
    friend void h5_write(h5::group g, std::string const &name, sub_hilbert_space const &hs) {
      auto gr = g.create_group(name);
      h5::write(gr, "index", hs.m_);
      h5::write(gr, "fock_states", hs.fock_states_);
    }

    /**
     * @brief Read a triqs::hilbert_space::sub_hilbert_space from HDF5.
     *
     * @param g `h5::group` to be read from.
     * @param name Name of the subgroup.
     * @param hs Subspace to be read into.
     */
    friend void h5_read(h5::group g, std::string const &name, sub_hilbert_space &hs) {
      auto gr = g.open_group(name);
      h5::read(gr, "index", hs.m_);
      h5::read(gr, "fock_states", hs.fock_states_);
      hs.fock_to_index_.clear();
      for (auto f : hs.fock_states_) hs.fock_to_index_.insert(std::make_pair(f, static_cast<int>(hs.fock_to_index_.size())));
    }

    private:
    int m_;
    std::vector<fock_state_t> fock_states_;
    boost::container::flat_map<fock_state_t, int> fock_to_index_;
  };

  /** @} */

} // namespace triqs::hilbert_space
