FROM intel/oneapi-hpckit:2025.2.0-0-devel-ubuntu24.04
ARG LLVM=19

RUN apt-get update && apt-get install -y lsb-release wget software-properties-common && \
      wget -O /tmp/llvm.sh https://apt.llvm.org/llvm.sh && chmod +x /tmp/llvm.sh && /tmp/llvm.sh ${LLVM} && \
      DEBIAN_FRONTEND=noninteractive apt-get install -y \
      g++ \
      git \
      vim \
      lldb-${LLVM} \
      hdf5-tools \
      libboost-dev \
      libclang-${LLVM}-dev \
      libc++-${LLVM}-dev \
      libc++abi-${LLVM}-dev \
      libfftw3-dev \
      libgmp-dev \
      libhdf5-dev \
      python3-clang-${LLVM} \
      python3-dev \
      python3-mako \
      python3-matplotlib \
      python3-numpy \
      python3-pip \
      python3-scipy \
      python3-venv

ENV PYTHON_VERSION=3.12 \
    CC=icx CXX=icpx CXXFLAGS="-stdlib=libc++" \
    CPLUS_INCLUDE_PATH=/usr/lib/llvm-${LLVM}/include/c++/v1 \
    VIRTUAL_ENV=/home/venv \
    PATH=/home/venv/bin:$PATH

RUN python3 -m venv --system-site-packages $VIRTUAL_ENV && pip install mpi4py cmake
