// This file is automatically generated by wrapped_aux.inst.py. Do not edit!
#include <c2py/c2py.hpp>
#include <nda/c2py/converters.hpp>
#include <triqs/c2py_converters/gf.hpp>
#include <triqs/c2py_converters/lattice.hpp>
#include <triqs/c2py_converters/mesh.hpp>
#include "./wrapped_aux_target_rank_3.hpp"

#include "wrapped_aux_target_rank_3.wrap.cxx"
